(function(){var bcUrl='https://support.google.com/adwords/answer/1722093';var rr=false;window['sc_refresh']= !rr ?true :false;})();</script>   <script data-id="page" nonce="+QS39bNwVq7uhiMgdJyo"></script>  <script nonce="+QS39bNwVq7uhiMg(function(){var au='';var bcUrl='https://support.google.com/adwords/answer/1722093';var dt=1;var ehc='adwords';var ehn='https://support.google.com';var fbapi='//ssl.gstatic.com/feedback/api.js';var fbid=0;var hc='adwords3';var hcid='177';var host='support.google.com';var key='support-content';var lang='en';var li=true;var mxp=[10800027,10800108,10800141,10800161,10800170,10800174];var ncc=2;var pid='1722093';var psd=[];var pvid='0005652c05e9c59f0a8e2047190a96ed';var pt=1;var query='hl\x3den\x26ref_topic\x3d3121941';var ii=false;var iro=1;var rs=1;var rr=false;var rtl=false;var sb_uri='';var skey='support-content';var visit_id='1-636542106558834897-864659477';var xsrf='ADZ_7r5FfdfD80AFLWJOZUdpZL9D:1518614635871';var legacy_url='google.com/support';var query_params=[{key:'hl',value:'en'},{key:'ref_topic',value:'3121941'}];var fragment='';var cl='185513751';var ff=true;var vid=2132430253;var auth_token='';window['sc_initPage']({'au':au,'bcUrl':bcUrl,'dt':dt,'ehc':ehc,'ehn':ehn,'fbapi':fbapi,'fbid':fbid,'hc':hc,'hcid':hcid,'host':host,'ii':ii,'iro':iro,'key':key,'lang':lang,'li':li,'mendel_ids':mxp || [],'ncc':ncc,'pid':pid,'psd':psd,'pvid':pvid,'pt':pt,'query':'?' + query,'rr':rr,'rs':rs,'rtl':rtl,'sb_uri':sb_uri,'skey':skey,'vid':vid,'visit_id':visit_id,'xsrf':xsrf,'query_params':query_params,'fragment':fragment,'cl':cl,'ff':ff,'auth_token':auth_token
});})();</script>   <script data-id="csi_lite" nonce="+QS39bNwVq7uhiMgdJyo">function Jk(){this.o=!1}
Jk.prototype.init=function(){window.addEventListener("load",function(){if(!this.o){var a=document.querySelector(".csi");if(a&&!a.value){var b=(new Date).getTime(),c=window.prt-window.start,d=b-window.start,e=window.performance&&window.performance.timing;e&&(c=window.prt-e.responseStart,d=b-e.responseStart);window.sc_trackStatsLatency({ol:99999<d?99999:d,prt:99999<c?99999:c});window.sc_pageLatency={ol:d,prt:c};a.value=1;this.o=!0}}}.bind(this),!1)};window.sc_initCsiLite=function(){window.sc_initCsiLiteDone||((new Jk).init(),window.sc_initCsiLiteDone=!0)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var curl='https://support.google.com/adwords/answer/1722093?hl\x3den\x26ref_topic\x3d3121941';window['sc_initCsiLite']({'curl':curl
});})();</script>    <script data-id="stats" nonce="+QS39bNwVq7uhiMgdJyo">function rq(a,b,c){var d=window.localStorage;if(!d)return!1;try{var e=c?JSON.stringify(b):b;d.setItem(a,e);return!0}catch(f){return window.sc_trackStatsEvent(ub,Yb,"local storage - persist local data"),!1}}
function sq(a,b,c){var d=window.localStorage;if(!d)return null;try{var e=d.getItem(a);if(!e)return null;c&&(e=JSON.parse(e));if(b){var f=window.localStorage;f&&f.removeItem(a)}return e}catch(g){return window.sc_trackStatsEvent(ub,Yb,"local storage - get local data"),null}}
function tq(a){this.o=a}
var uq={"primary-button":1,"action-button":2,"default-button":3,"product-link":4};p=tq.prototype;p.init=function(){window.sc_registerPageClickHandlers([this.Oj.bind(this),this.Fj.bind(this)])};p.Bk=function(){var a=A(),b=sq("statsDeferred",!0,!0);b&&(b.event.common_params.context_params.visit_id=a.visit_id,vq(b.event,void 0,b.ehc,b.event.common_params.context_params.experiment_id));if(window.sc_refresh){a=parseInt(sq("refererViewId",!1,!1),10);a=isNaN(a)?0:a;b=wq(this,1);var c=b.resource.stats[0].page_view={changelist:parseInt(this.o.cl,10)};a&&(c.referer_view_id=a);vq(b)}this.Me()};p.Me=function(a){a=(a||document).querySelectorAll("[data-stats-imp]");for(var b=[],c=0;c<a.length;c++){var d=xq(a[c],"data-stats-ve",eb.id,!0),e=xq(a[c],"data-stats-id"),f=xq(a[c],"data-stats-idx");b.push([parseInt(d,10),e,f])}0!=b.length&&this.Le(b)};p.Ak=function(a,b){b=b?b.id:parseInt(xq(a,"data-stats-ve",eb.id,!0),10);var c=xq(a,"data-stats-id");a=xq(a,"data-stats-idx");this.Le([[b,c,a]])};p.Le=function(a){for(var b=wq(this,3),c=b.resource.stats[0].impressions=[],d=0;d<a.length;d++){var e=a[d],f={type:e[0]};e[1]&&(f.id=e[1]);yq(f,e[2]);c.push(f)}vq(b)};p.Xg=function(a,b,c,d,e){a=a.id;var f=b.id;b=wq(this,5);a={type:a,action:f};c&&(a.id=c);yq(a,d);(b.resource.stats[0].events=[]).push(a);vq(b,e)};p.Ta=function(a,b,c,d,e,f){b||(b=parseInt(xq(a,"data-stats-ve",eb.id,!0),10),b=zq(Fb,b));c||(c=parseInt(xq(a,"data-stats-action",Gb.id,f),10),c=zq(gc,c));d=d||xq(a,"data-stats-id",void 0,f);a=e||xq(a,"data-stats-idx",void 0,f);this.Xg(b,c,d,a)};function zq(a,b){var c,d;for(d in a){var e=a[d];if(e.id==b)return e;0==e.id&&(c=e)}return c}
p.Yg=function(a){var b=wq(this,2);b.resource.stats[0].latency=a;vq(b)};p.Ck=function(a){var b=wq(this,6);b.resource.stats[0].time_on_page=a;vq(b)};p.Oj=function(a){a.hc_internal&&rq("refererViewId",A().vid)};p.Fj=function(a){if(!a.href||"#"!=a.href){var b=a.element;if(b){a:{var c;if(c=b){b:{for(c=b;c;){if(c.hasAttribute&&c.hasAttribute("data-stats-ignore")){c=!0;break b}c=c.parentNode}c=!1}c=!c}if(c)for(;b;){if(b.hasAttribute&&b.hasAttribute("data-stats-action")||"A"==b.tagName||ge(b))break a;b=b.parentNode}b=null}if(b){c=Aq(a);var d=b,e=xq(d,"data-stats-ve",eb.id,!0);var f=(f=d.getAttribute("data-stats-toggle-class"))?!y(d,f):0==d.checked;var g=xq(d,"data-stats-action",f?fc.id:Ob.id),l=xq(d,"data-stats-id",d.href,!0);f=wq(this,4);e=f.resource.stats[0].click_tracking={click_method:c,type:parseInt(e,10),action:parseInt(g,10)};l&&(e.id=l);yq(e,xq(d,"data-stats-idx"));for(var m in uq)if(y(d,m)){e.content_attribute={style:uq[m]};break}a=a.event;switch(c){case 2:m=b;a.preventDefault();vq(f,this.jf.bind(this,m));break;case 3:vq(f);break;case 1:rq("statsDeferred",{event:f,ehc:A().ehc},!0)||(m=b,a.preventDefault(),vq(f,this.jf.bind(this,m)))}}}}};function wq(a,b){var c=A();b={common_params:{language:c.lang,context_params:{connection_class:c.ncc,device_type:c.dt,page_type:c.pt,referer:c.bcUrl,request_source:c.rs,visit_id:c.visit_id,view_id:c.vid,experiment_id:[10800112]}},resource:{stats:[{type:b,request_state:{view_id:c.vid,initial_request_origin:c.iro,page_id:c.pid}}]}};var d=c.mendel_ids;if(d&&d.length)for(var e=0;e<d.length;e++)b.common_params.context_params.experiment_id.push(d[e]);if(a.o.exp){if(a=a.o.exp){d=[];e=0;for(var f;f=a[e];e++)f&&
(f=f.active_groups)&&d.push(f);d=d.join(";")}else d="";a=b.common_params.context_params.gkms_experiment=[];d=d.split(";");for(e=0;e<d.length;e++)f=d[e].split("::"),2==f.length&&a.push({experiment_id:f[0],group_id:f[1]})}c.request_attributes&&(b.resource.stats[0].request_state.request_attributes=c.request_attributes);return b}
p.jf=function(a){if(a.getAttribute&&a.getAttribute("data-stats-delay-url"))var b=a.getAttribute("data-stats-delay-url");else if("A"===a.nodeName&&a.href){if("_blank"===a.target){window.open(a.href,"_blank");return}b=a.href}(a=window.sc_delayLocationHandler)&&a instanceof Function?a(b):E(b)};function xq(a,b,c,d){c=void 0!==c?c.toString():void 0;if(d)for(;a;)if(a.getAttribute&&a.getAttribute(b)){c=a.getAttribute(b);break}else a=a.parentNode;else a.getAttribute&&a.getAttribute(b)&&(c=a.getAttribute(b));return c?c.toLowerCase():void 0}
function Aq(a){var b=a.element.getAttribute("data-stats-method");if(b)switch(b.toUpperCase()){case "DELAY":return 2;case "IMMEDIATE":return 3;case "DEFER":return 1}return a.blank?3:a.external?2:a.hc_internal?1:3}
function yq(a,b){b&&(b=b.split(","),b[0]&&(a.idx=parseInt(b[0],10)||0),b[1]&&(a.count=parseInt(b[1],10)||0))}
function vq(a,b,c,d){B({httpMethod:"POST",endpoint:"metrics",params:{v:window.sc_useNewMetricsApi?"1":"0"},Xa:a,fe:c,Na:b,ab:b,Hk:!0,Sf:d});C(document,"sc_statsEvent",a)}
function Bq(){this.w=O;this.o=Date.now()}
Bq.prototype.report=function(a){this.w.Yg({type:a,duration_ms:Date.now()-this.o})};var O;window.sc_initStats=function(a){if(!window.sc_refresh){var b=window.sc_trackStatsScopedImpressions;if(b){b(window.sc_scope);return}}O=new tq(a);O.init();window.sc_trackStatsEvent=O.Xg.bind(O);window.sc_trackStatsEventByElement=O.Ta.bind(O);window.sc_trackStatsScopedImpressions=O.Me.bind(O);window.sc_trackStatsImpressions=O.Le.bind(O);window.sc_trackStatsImpressionByElement=O.Ak.bind(O);window.sc_trackStatsLatency=O.Yg.bind(O);window.sc_trackStatsPageView=O.Bk.bind(O);window.sc_trackStatsTimeOnPage=O.Ck.bind(O)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var cl='185513751';var exp=[{active_groups:'AdWords_CSat_Dissat_Drivers_Experiment::Control_group'},{active_groups:'AdWords_Content_Template_Experiment::Control_group'},{active_groups:'pre_impression::half_imp'},{active_groups:'bb3_control::control'},{active_groups:'top_nav_remove::control'},{active_groups:'grow_callouts_test::test'},{active_groups:'gold_control::control'},{active_groups:'fix_disapproved_ad_control::control'},{active_groups:'currency_time_test_2::test'},{active_groups:'pause_resume_camp_test::test'},{active_groups:'approval_process_test::test'},{active_groups:'under_review_test::test'},{active_groups:'about_suspended_test::test'},{active_groups:'reactivate_canceled_test::test'},{active_groups:'finding_ads_test::test'},{active_groups:'aw_experience_test::test'},{active_groups:'aw_mgr_test::test'}];var ref='https://support.google.com/adwords/topic/3119116?hl\x3den\x26ref_topic\x3d3119071,3181080,3126923,';window['sc_initStats']({'cl':cl,'exp':exp,'ref':ref
});})();</script>    <script data-id="visit_manager" nonce="+QS39bNwVq7uhiMgdJyo">function Iq(a){this.w=a;Jq(this)}
function Jq(a){a.o();Ya.push(function(a){$a(a)||"#"==a.getAttribute("href")[0]||this.o()}.bind(a))}
Iq.prototype.H=function(a){a.hc_internal&&this.o()};Iq.prototype.o=function(){var a=A(),b=(new Date((new Date).getTime()+this.w.vttl)).toUTCString(),c=document.createElement("a");c.href=a.ehn;document.cookie="SUPPORT_CONTENT="+a.visit_id+";domain="+c.hostname+";path=/;max-age="+Math.floor(this.w.vttl/1E3)+";expires="+b+";Secure"};window.sc_initVisitManager=function(a){a=new Iq(a);window.sc_visitManagerProcessClick=a.H.bind(a);window.sc_setVisitIdCookie=a.o.bind(a)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var vttl=1800000;window['sc_initVisitManager']({'vttl':vttl
});})();</script>  <script data-id="top_timer" nonce="+QS39bNwVq7uhiMgdJyo">function No(a){this.S=a;this.o=[];this.R="hidden";this.T=this.w=this.H=0;Oo(this)}
function Oo(a){if(-1!=a.S.delays){for(var b=a.S.delays.split(","),c=0;c<b.length;c++)a.o.push(parseInt(b[c],10));b="";var d=["moz","ms","webkit"];for(c=0;c<d.length;c++){b=d[c];var e=b+"Hidden";"undefined"!=typeof document[e]&&(a.R=e)}document.addEventListener(b+"visibilitychange",a.V.bind(a));Po(a,a.o[0]);document.addEventListener("pjaxunload",function(){Qo(this);this.o=[]}.bind(a))}}
No.prototype.V=function(){document[this.R]?this.w&&Qo(this):!this.w&&0<this.o.length&&Po(this,this.T)};function Po(a,b){a.H=Date.now()+b;a.w=window.setTimeout(a.W.bind(a),b)}
function Qo(a){a.T=a.H-Date.now();window.clearTimeout(a.w);a.w=0}
No.prototype.W=function(){window.sc_trackStatsTimeOnPage({top:this.o[0]/1E3,page_view_id:A().pvid});var a=this.o.shift();0<this.o.length?Po(this,this.o[0]-a):this.w=0};window.sc_initTopTimer=function(a){new No(a)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var delays='2000,5000,10000,30000,60000';if (window['sc_refresh']== true){window['sc_initTopTimer']({'delays':delays
});}
})();</script>   <script data-id="bubble" nonce="+QS39bNwVq7uhiMgdJyo">function Ai(a,b,c,d,e,f,g){this.V=a;this.ta=b;this.ua=c;this.ha=d;this.ka=e;this.va=f;this.ma=g;this.T=this.ne.bind(this);this.W=this.position.bind(this);this.ra=this.zj.bind(this);this.H=this.S=this.o=this.w=null;this.R=!1;a:{for(a=this.V;a;){if("fixed"==window.getComputedStyle(a).position){a=!0;break a}a=a.offsetParent}a=!1}this.R=a;this.w=document.createElement("div");this.w.className="sc-bubble";this.R&&(this.w.style.position="fixed");this.o=document.createElement("div");this.o.className="sc-bubble-box";this.ma&&(this.o.setAttribute("role","dialog"),this.o.tabIndex=0);this.w.appendChild(this.o);this.o.appendChild(this.ua);this.va&&(this.S=document.createElement("div"),this.S.className="sc-bubble-close",this.o.appendChild(this.S));this.H=document.createElement("div");this.w.appendChild(this.H);document.body.appendChild(this.w)}
p=Ai.prototype;p.show=function(){window.addEventListener("resize",this.W);window.addEventListener("scroll",this.W);document.addEventListener("mousedown",this.T);document.addEventListener("touchstart",this.T);document.addEventListener("keydown",this.ra);this.position();x(this.w,"sc-bubble-show",!0);this.ma&&this.o.focus()};p.ne=function(a){a&&this.w.contains(a.target)&&a.target!=this.S||(document.removeEventListener("keydown",this.ra),document.removeEventListener("mousedown",this.T),document.removeEventListener("touchstart",this.T),window.removeEventListener("scroll",this.W),window.removeEventListener("resize",this.W),x(this.w,"sc-bubble-show",!1),C(this.w,"bubblehide"))};p.position=function(){this.H.className="sc-bubble-arrow sc-bubble-arrow-"+this.ta;for(var a={x:0,y:0,Ja:this.H.offsetWidth,h:this.H.offsetHeight},b={x:0,y:0,Ja:this.o.offsetWidth,h:this.o.offsetHeight},c,d=c=0,e=this.V;e;)c+=e.offsetLeft,d+=e.offsetTop,e=e.offsetParent;c={x:c,y:d,Ja:this.V.offsetWidth,h:this.V.offsetHeight};d={x:this.R?0:window.pageXOffset,y:this.R?0:window.pageYOffset,Ja:document.documentElement.clientWidth,h:document.documentElement.clientHeight};e=this.ta;!A().rtl||"left"!=e&&
"right"!=e||(e=Bi(e));var f=Ci(e,c,a,b,d);if(!(0>=f)){var g=Bi(e);e=f<=Ci(g,c,a,b,d)?e:g}switch(e){case "top":a.y=c.y-a.h;b.y=a.y-b.h;break;case "right":a.x=c.x+c.Ja;b.x=a.x+a.Ja;break;case "bottom":a.y=c.y+c.h;b.y=a.y+a.h;break;case "left":a.x=c.x-a.Ja,b.x=a.x-b.Ja}switch(e){case "top":case "bottom":a.x=c.x+(c.Ja-a.Ja)/2;b.x=a.x-(b.Ja-a.Ja)*this.ha/100-this.ka;b.x=Math.min(b.x,d.x+d.Ja-b.Ja);b.x=Math.max(b.x,d.x,a.x+a.Ja-b.Ja);b.x=Math.min(b.x,a.x);break;case "right":case "left":a.y=c.y+(c.h-a.h)/
2,b.y=a.y-(b.h-a.h)*this.ha/100-this.ka,b.y=Math.min(b.y,d.y+d.h-b.h),b.y=Math.max(b.y,d.y,a.y+a.h-b.h),b.y=Math.min(b.y,a.y)}this.H.className="sc-bubble-arrow sc-bubble-arrow-"+Bi(e);this.H.style.left=a.x+"px";this.H.style.top=a.y+"px";this.o.style.left=b.x+"px";"top"==e?(this.o.style.bottom=this.o.offsetParent.offsetHeight-a.y+"px",this.o.style.top=""):(this.o.style.top=b.y+"px",this.o.style.bottom="")};function Ci(a,b,c,d,e){switch(a){case "top":return e.y-b.y+c.h+d.h;case "right":return b.x+b.Ja+c.Ja+d.Ja-e.x-e.Ja;case "bottom":return b.y+b.h+c.h+d.h-e.y-e.h;case "left":return e.x-b.x+c.Ja+d.Ja;default:return 0}}
function Bi(a){switch(a){case "top":return"bottom";case "right":return"left";case "bottom":return"top";case "left":return"right";default:return""}}
p.La=k("w");p.zj=function(a){27==a.which&&this.ne()};window.sc_createBubble=function(a,b,c,d,e,f,g){a=new Ai(a,b,c,d,e,f,g);return{show:a.show.bind(a),hide:a.ne.bind(a),position:a.position.bind(a),getElement:a.La.bind(a)}};</script>      <script data-id="spinner" nonce="+QS39bNwVq7uhiMgdJyo">function ro(a){this.o=document.createElement("div");this.o.className="mspin "+(a||"mspin-medium");a=document.createElement("div");a.appendChild(document.createElement("div"));this.o.appendChild(a)}
ro.prototype.La=k("o");ro.prototype.show=function(){this.o.style.display="inline-block"};ro.prototype.w=function(){this.o.style.display="none"};window.sc_createSpinner=function(a){a=new ro("small"==a?"mspin-small":"mspin-medium");return{getElement:a.La.bind(a),show:a.show.bind(a),hide:a.w.bind(a)}};</script>        <script data-id="render_api" nonce="+QS39bNwVq7uhiMgdJyo">function Ln(){}
Ln.prototype.request=function(a,b,c,d,e,f,g){var l=A(),m="render_api"+(1E9*Math.random()>>>0),n=[["js_request_id",m],["rr",1],["lc",1]],u=Mn();0<u.length&&n.push(["loaded_js",u.join(",")]);e&&Nn(e,n);Nn(On(),n);if(l.query_params){u=[];for(e=0;e<l.query_params.length;e++){var D=l.query_params[e];u.push([D.key,D.value])}Nn(u,n)}u={};u.hl=l.lang;u.page_type=a;u.id=b;u.visit_id=l.visit_id;u.extra_param=[];u.component=[];for(e=0;e<n.length;e++)u.extra_param.push(n[e][0]+"."+n[e][1]);if(f)for(e=0;e<f.length;e++)u.component.push(f[e]);g&&(u.containing_page_type=g);d&&(window[m]=function(a){d(a.getChild(m))});B({httpMethod:"GET",endpoint:"render",params:u,Na:function(a){var b=null;try{b=JSON.parse(a.responseText)}catch(cd){}if(b&&b.html){c.innerHTML=b.html;for(a=c.getElementsByTagName("style");0<a.length;)document.head.appendChild(a[0]);this.o(c)}}.bind(this)})};function Nn(a,b){for(var c={},d=0;d<b.length;d++)c[b[d][0]]=!0;for(d=0;d<a.length;d++){var e=a[d][0],f=a[d][1];c[e]||b.push([e,f])}}
function Mn(){for(var a=[],b=document.getElementsByTagName("script"),c=0;c<b.length;c++){var d=b[c].getAttribute("data-id");d&&a.push(d)}return a}
function On(){for(var a=[],b=/([^?&=]+)=([^&]+)/g,c;c=b.exec(A().query);)a.push([c[1],decodeURIComponent(c[2])]);return a}
Ln.prototype.o=function(a){window.sc_scope=a;for(var b=a.getElementsByTagName("script");0<b.length;){var c=b[0];c.parentNode.removeChild(c);if(c.src){b=td();b.setAttribute("data-id",c.getAttribute("data-id"));b.onload=this.o.bind(this,a);a=ud(c.src);b.src=ed(a);document.head.appendChild(b);return}eval(c.innerHTML)}delete window.sc_scope};window.sc_initRenderApi=function(){if(!window.sc_renderRequest){var a=new Ln;window.sc_renderRequest=a.request.bind(a)}};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">window['sc_initRenderApi']();</script>    <script data-id="search_material_onebar" nonce="+QS39bNwVq7uhiMgdJyo">function Yn(a){this.o=a}
;function Zn(a){this.o=a}
w(Zn,Yn);Zn.prototype.Ga=function(){return this.o.xa};function $n(a){this.o=a}
w($n,Yn);$n.prototype[Fd]=!0;p=$n.prototype;p.Gf=function(a,b,c,d){var e=this;this.o.za(a,function(a){return b.call(d||r,new Zn(a,e))},c)};p.Rf=function(){throw Error("Not implemented.");};p.Hf=function(){throw Error("Not implemented.");};p.Oe=function(){throw Error("Not implemented.");};p.qd=function(){throw Error("Not implemented.");};p.ae=function(){throw Error("Not implemented.");};p.Ac=function(){throw Error("Not implemented.");};function ao(a,b){this.o=a;this.w=b||null}
w(ao,Yn);ao.prototype.then=function(a,b,c){var d;a&&(d=bo(this,a));this.o.aa(d,b,c)};function bo(a,b){var c=a.w;return c?function(a){b.call(this,new c(a))}:b}
;function co(a){this.o=a}
w(co,$n);function eo(a){this.o=a||gbar.a;this.H=this.w=null}
w(eo,Yn);eo.o=void 0;eo.nd=function(){return eo.o?eo.o:eo.o=new eo};function fo(){var a=eo.nd();a.H||(a.H=new ao(a.o.bb(),co));return a.H}
;function go(){}
go.prototype.init=function(){fo().then(function(a){var b=a.o.gj();b.addEventListener("submit",function(a){a.preventDefault();if(a=b.elements.q.value)window.sc_trackStatsEvent(ib,Zb,a),E(G(new hc(b.action),"q",a).toString())})})};v("hcfe.SearchMaterialOneBar",go);</script>   <script data-id="one_google_bar" nonce="+QS39bNwVq7uhiMgdJyo">function aq(a){this.o=a}
w(aq,$n);function bq(){var a=eo.nd();a.w||(a.w=new ao(a.o.bf(),aq));return a.w}
function cq(){this.R=window.sc_scope||document;this.w=null;this.o=!1;this.S=!!this.R.querySelector(".always-show-hamburger")}
function dq(a){var b=new cq;b.w=a;var c=b.R.querySelector(".one-google-bar-placeholder");c&&(b.w.current_url=window.location.href,b.w.search_query=Oa("q"),B({httpMethod:"POST",endpoint:"onebar",Xa:b.w,Na:function(a){try{var d=JSON.parse(a.responseText);eq(d,c);fq(b)}catch(f){}}}))}
function fq(a){bq().then(function(b){a.H=b;a.o=1024>document.body.clientWidth;window.addEventListener("resize",function(){var b=1024>document.body.clientWidth;a.o!=b&&(gq(a,b||a.S),a.o=b)});gq(a,a.o||a.S);hq(a)})}
function gq(a,b){b?a.H.o.pm("default"):a.H.o.pm("none")}
function hq(a){var b=a.H.o.ph();b&&(a=!!a.R.querySelector("#material-bar-custom-product-name"),!b.querySelector("img")&&a&&(b.style.display="none"))}
function eq(a,b){eval(a.in_head_script);var c=document.createElement("style");c.innerHTML=a.in_head_style;document.head.appendChild(c);var d=document.createElement("div");d.className="gaiabar";x(d,"loading",!0);d.innerHTML=a.html;b.parentNode.appendChild(d);document.body.insertAdjacentHTML("beforeend",a.end_of_body_html);eval(a.after_bar_script);eval(a.end_of_body_script);(new go).init();var e=0,f=window.setInterval(function(){var a=d.querySelector("#sc-burger-top");if(d.firstChild.clientHeight<=
b.clientHeight&&a&&"hidden"==window.getComputedStyle(a).visibility||100<=e)clearInterval(f),d.children[1]&&(d.children[1].style.height=b.clientHeight+"px"),x(d,"loading",!1),b.parentNode.replaceChild(d,b),window.sc_initFeedback&&window.sc_initFeedback();e++},10)}
window.sc_loadOneBar=function(a){dq(a)};window.sc_initOneBar=function(){fq(new cq)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">window['sc_initOneBar']();</script>     <script data-id="contactflow_trigger" nonce="+QS39bNwVq7uhiMgdJyo">function Ek(){this.R=window.sc_scope||document;this.o=this.w=null;Fk(this)}
function Fk(a){a.w=a.R.querySelector(".contact-flow-trigger");if(a.w){a.w.addEventListener("click",function(a){!Xa()&&window.sc_createBubble&&(a.preventDefault(),Sa("contact","1"),this.H())}.bind(a));a.H();var b=a.H.bind(a);window.addEventListener("hashchange",b);document.addEventListener("pjaxunload",function(){window.removeEventListener("hashchange",b)})}}
Ek.prototype.H=function(){"1"==Ra("contact")&&Gk(this)};function Gk(a){if(!Xa()&&window.sc_createBubble||!a.w)if(window.sc_trackStatsEvent(lb,Kb),a.o)a.o.show();else{var b=document.createElement("div");a.o=window.sc_createBubble(a.w,"bottom",b,100,0,!1,!0);x(a.o.getElement(),"contact-flow-trigger-bubble",!0);if(window.sc_createSpinner){var c=window.sc_createSpinner();b.appendChild(c.getElement());a.o.show()}window.sc_renderRequest("CONTACT_FLOW","",b,a.o.show,[["referer",Wa()]],["PCT_TITLE"]);a.o.getElement().addEventListener("bubblehide",function(){Ta("contact");window.sc_trackStatsEvent(lb,Lb)}.bind(a))}else a.w.click()}
window.sc_initContactFlowTrigger=function(){new Ek};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">window['sc_initContactFlowTrigger']();</script>             <script data-id="search" nonce="+QS39bNwVq7uhiMgdJyo">function ho(a){this.o=null;this.w=!1;this.R=a}
function io(a){x(a.o,"show-search");var b=document.getElementById("search-toggle");if(y(a.o,"show-search")){var c=document.getElementById("search-box");c&&c.focus();b.setAttribute("aria-label",a.R.close)}else b.setAttribute("aria-label",a.R.search);a=document.getElementsByClassName("search-toggle");for(b=0;b<a.length;b++)x(a[b],"active")}
ho.prototype.H=function(){this.w?window.history.go(-1):io(this)};ho.prototype.S=function(a){if(y(a,"active")){if(a=document.getElementById("search-box"))a.value="",a.focus()}else io(this)};ho.prototype.init=function(){if(this.o=document.getElementById("search-container")){this.w=y(this.o,"always-show-search");var a=this.o.getElementsByTagName("form")[0];if(a){var b=document.getElementById("search-back"),c=document.getElementById("search-toggle"),d=document.getElementsByClassName("search-overlay")[0];b&&b.addEventListener("click",this.H.bind(this));c&&c.addEventListener("click",this.S.bind(this,c));d&&d.addEventListener("click",this.H.bind(this));var e=!1;a.addEventListener("submit",function(b){b.preventDefault();(b=a.elements.q.value)&&!e&&(window.sc_trackStatsEvent(ib,Zb,b),e=!0,E(G(new hc(a.action),"q",b).toString()))})}}};window.sc_initSearch=function(a){(new ho(a)).init()};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var close='Close';var search='Search';window['sc_initSearch']({close:close,search:search
});})();</script>     <script data-id="search_full_layout" nonce="+QS39bNwVq7uhiMgdJyo">function Wn(){this.o=window.sc_scope||document;Xn(this)}
function Xn(a){var b=a.o.querySelector(".non-one-bar form, .gaiabar form");if(b){var c=!1;b.addEventListener("submit",function(a){a.preventDefault();(a=b.elements.q.value)&&!c&&(window.sc_trackStatsEvent(ib,Zb,a),c=!0,E(G(new hc(b.action),"q",a).toString()))})}}
window.sc_initSearchFullLayout=function(){new Wn};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">window['sc_initSearchFullLayout']();</script>    <script data-id="search_autocomplete" nonce="+QS39bNwVq7uhiMgdJyo">function Un(a){var b=window.sc_scope;this.W=a;this.H=b||document;this.R=this.o=this.w=null;this.V=!1;this.S=null;Vn(this)}
function Vn(a){a.w=a.H.querySelector("#gbqf, .gaiabar form, .non-one-bar form, .promoted-search__form");a.o=a.H.querySelector('#gbqfq, .gaiabar form input[name="q"], .non-one-bar input[name="q"], .promoted-search__input');a.w&&a.o&&(a.w.id="search-form",a.S=new Th,a.S.install(a.o,a.W.eid,A().lang,a.T.bind(a),a.ha.bind(a),["HELP_ARTICLE","SUPPORT_THREAD"],void 0,void 0,"search-form"),a.R=a.H.querySelector('#gbqfb, .gaiabar form button[role="button"], .promoted-search__search-button'),a.R&&a.R.addEventListener("click",function(a){a.preventDefault();this.T()}.bind(a)))}
Un.prototype.T=function(){var a;if(a=!this.V&&""!=this.o.value.trim()){a=this.o.value.trim();var b=Oa("q");a=!(a&&a==b)}a&&(window.sc_trackStatsEvent(ib,this.S.w?$b:Zb,this.o.value),this.w.submit(),this.V=!0)};Un.prototype.ha=function(a,b){var c=b.url;window.sc_trackStatsEvent(ib,Sb,c,void 0,function(){E(c)})};window.sc_initSearchAutocomplete=function(a){function b(){new Un(a)}
b();window.sc_reinitSearchAutocomplete=b};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var eid=73067;window['sc_initSearchAutocomplete']({'eid':eid
});})();</script>     <script data-id="language_selector" nonce="+QS39bNwVq7uhiMgdJyo">function an(){this.w=window.location}
an.prototype.init=function(a){a=(a||document).querySelectorAll("form.language-selector");for(var b=0;b<a.length;++b){var c=a[b].querySelector('select[name="hl"]');c&&c.addEventListener("change",this.o.bind(this,c))}};an.prototype.o=function(a){E(G(new hc(this.w.href),"hl",a.value).toString())};window.sc_initLanguageSelector=function(){(new an).init(window.sc_scope)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">window['sc_initLanguageSelector']();</script>    <script data-id="lazy_load" nonce="+QS39bNwVq7uhiMgdJyo">function bn(a){this.V=a;this.o={};this.H=0;this.w=null;this.R=""}
bn.prototype.init=function(a){var b=0<this.H;a=(a||document).getElementsByClassName("img-2g");for(var c=0,d;d=a[c];c++)d.getAttribute("data-src")&&(this.o[c]=a[c],this.H++);0==this.H||b||(this.R="scroll"in window?"scroll":"touchmove",this.w=this.T.bind(this),window.addEventListener(this.R,this.w),window.addEventListener("load",this.w),document.addEventListener("imgLazyLoad",this.w,!1))};function cn(a){if(!a)return!1;a=a.getBoundingClientRect();return 0<a.bottom&&0<a.right&&a.left<(window.innerWidth||document.documentElement.clientWidth)&&a.top<(window.innerHeight||document.documentElement.clientHeight)}
bn.prototype.S=function(a){var b=this.o[a];if(cn(b)){var c=new Image;c.src=b.getAttribute("data-src");c.style.cssText=b.style.cssText;var d=b.getAttribute("alt");d&&c.setAttribute("alt",d);(d=b.getAttribute("title"))&&c.setAttribute("title",d);(d=b.getAttribute("class"))&&c.setAttribute("class",d);b.parentNode.replaceChild(c,b);delete this.o[a];this.H--;0==this.H&&(window.removeEventListener(this.R,this.w),document.removeEventListener("imgLazyLoad",this.w,!1))}};bn.prototype.T=function(){for(var a in this.o)this.o.hasOwnProperty(a)&&cn(this.o[a])&&window.setTimeout(this.S.bind(this,a),this.V.delay)};window.sc_initLazyLoad=function(a){var b=window.sc_lazyImageLoader;b||(a=new bn(a),b=a.init.bind(a),window.sc_lazyImageLoader=b);b(window.sc_scope)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var delay=500;window['sc_initLazyLoad']({'delay':delay});})();</script>                   <script data-id="zippy" nonce="+QS39bNwVq7uhiMgdJyo">function np(){this.o=window.sc_scope||document}
np.prototype.init=function(){for(var a=this.o.querySelectorAll(".zippy"),b=null,c=0;c<a.length;c++){var d=c+1,e=a[c],f=e.nextElementSibling;if(f&&("DIV"===f.nodeName||"P"===f.nodeName)){var g=document.createElement("DIV");x(g,"zippy-container",!0);e.parentNode.replaceChild(g,e);g.appendChild(e);var l=document.createElement("DIV");l.className="zippy-overflow";f.parentNode.insertBefore(l,f);l.appendChild(f);x(e,"index"+d,!0);x(f,"zippy-content",!0);op(e)?(x(e,"goog-zippy-expanded",!0),f.removeAttribute("aria-hidden"),e.setAttribute("aria-expanded",!0),f.style.marginTop=0,!b&&e.name&&pp(A().query+window.location.hash,e.name)&&(b=e)):(qp(f),f.style.height=f.style.padding=0,f.setAttribute("aria-hidden",!0),e.setAttribute("aria-expanded",!1),x(f,"zippy-hidden",!0),x(e,"goog-zippy-collapsed",!0));window.addEventListener("resize",function(a){y(a,"zippy-hidden")&&rp(a,"",function(){qp(a)}.bind(this))}.bind(this,f));(l=l.nextElementSibling)&&y(l,"zippy")||x(g,"zippy-last",!0);e.tabIndex=0;e.setAttribute("role","button");e.setAttribute("aria-haspopup","true");e.addEventListener("click",this.w.bind(this,f,e));e.addEventListener("keydown",this.R.bind(this,f,e));e.setAttribute("data-stats-ve",gb.id);e.setAttribute("data-stats-imp","");e.setAttribute("data-stats-idx",d+","+a.length);e.setAttribute("data-stats-ignore","");(d=e.getAttribute("id"))||(d=e.getAttribute("name"));d&&e.setAttribute("data-stats-id",d);sp(this,e,f)}}b&&b.scrollIntoView()};function rp(a,b,c){a.style.transition!=b?(a.style.transition=b,window.setTimeout(c,0)):c()}
function op(a){return y(a,"zippy-expand")||!!a.name&&pp(A().query+window.location.hash,a.name)}
function pp(a,b){return(new RegExp("[?#&,]"+Pa(b)+"(?:[#&,]|$)")).test(a)}
function qp(a){a.style.marginTop=-a.offsetHeight+"px"}
np.prototype.w=function(a,b){x(a,"zippy-hidden");x(b,"goog-zippy-expanded");x(b,"goog-zippy-collapsed");if(y(b,"goog-zippy-expanded")){a.removeAttribute("aria-hidden");b.setAttribute("aria-expanded",!0);var c=Ib;tp(a)}else a.setAttribute("aria-hidden",!0),b.setAttribute("aria-expanded",!1),c=Jb,rp(a,"margin-top .218s ease-out",function(){qp(a)}.bind(this));window.sc_trackStatsEventByElement(b,gb,c)};np.prototype.R=function(a,b,c){switch(c.which){case 13:case 32:c.preventDefault(),this.w(a,b)}};function tp(a){up(a);a.style.height=a.style.padding="";rp(a,"margin-top .218s ease-out",function(){a.style.overflow="auto";a.style.marginTop=0});C(document,"imgLazyLoad")}
function up(a){a=a.getElementsByClassName("goog-zippy-collapsed");for(var b=0;b<a.length;b++){var c=a[b].parentNode.nextElementSibling;c&&(c=c.firstChild)&&qp(c)}}
function sp(a,b,c){if(b.name)for(var d=a.o.getElementsByTagName("a"),e=0;e<d.length;e++){var f=d[e];pp(f.href,b.name)&&f.addEventListener("click",a.H.bind(a,b,c))}}
np.prototype.H=function(a,b){y(a,"goog-zippy-expanded")||(x(b,"zippy-hidden",!1),x(a,"goog-zippy-expanded",!0),x(a,"goog-zippy-collapsed",!1),tp(b),window.sc_trackStatsEventByElement(a,gb,Ib))};window.sc_initZippy=function(){(new np).init()};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">window['sc_initZippy']();</script>    <script data-id="screenshot" nonce="+QS39bNwVq7uhiMgdJyo">function Pn(a){this.w=a;this.S=parseInt(this.w.getAttribute("width"),10);this.R=parseInt(this.w.getAttribute("height"),10);this.o=null;a:{for(a=0;a<Qn.length;a++){var b=Qn[a];if(y(this.w,b)){Rn(this,"screenshot-container");this.o.appendChild(Sn("zoom-in","M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14zM12 10h-2v2H9v-2H7V9h2V7h1v2h2v1z"));this.o.appendChild(Sn("zoom-out","M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14zM7 9h5v1H7z"));a=parseInt(this.w.getAttribute("data-top"),10);b=parseInt(this.w.getAttribute("data-right"),10);var c=parseInt(this.w.getAttribute("data-bottom"),10),d=parseInt(this.w.getAttribute("data-left"),10);if(!(isNaN(a)||isNaN(b)||
isNaN(c)||isNaN(d))){var e=document.createElement("div");e.className="highlight";e.style.top=a/this.R*100+"%";e.style.left=d/this.S*100+"%";e.style.width=(b-d)/this.S*100+"%";e.style.height=(c-a)/this.R*100+"%";this.o.appendChild(e)}this.o.addEventListener("click",this.T.bind(this));window.addEventListener("resize",this.H.bind(this));this.H();break a}}for(a=0;a<Tn.length;a++)if(b=Tn[a],y(this.w,b)){Rn(this,b);break}}}
var Qn=["screenshot","full-screen--mini"],Tn=["full-screen","top-left","top-right"];function Rn(a,b){a.o=document.createElement("div");a.o.className=b;a.w.parentNode.replaceChild(a.o,a.w);a.o.appendChild(a.w)}
function Sn(a,b){var c=document.createElementNS("http://www.w3.org/2000/svg","svg");c.setAttribute("viewBox","0 0 24 24");c.setAttribute("class",a);a=document.createElementNS("http://www.w3.org/2000/svg","path");a.setAttribute("d",b);c.appendChild(a);return c}
Pn.prototype.T=function(a){this.o.contains(a.target)&&(x(this.o,"expanded"),a=y(this.o,"expanded"),window.sc_trackStatsEvent(sb,a?Ib:Jb),this.H())};Pn.prototype.H=function(){this.o.style.width=y(this.o,"expanded")?"100%":"33%"};window.sc_initScreenshots=function(){for(var a=(window.sc_scope||document).querySelectorAll(".screenshot, .full-screen, .full-screen--mini, .top-left, .top-right"),b=0;b<a.length;b++)new Pn(a[b])};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">window['sc_initScreenshots']();</script>     <script data-id="promotion_tracker" nonce="+QS39bNwVq7uhiMgdJyo">function Hn(a){this.o=a}
window.sc_trackPromotion=function(a){var b=window.sc_useNewPrefinsertApi;a=new Hn(a);var c=A();B({httpMethod:"POST",endpoint:b?"preferences":"prefinsert",params:{v:b?"1":"0"},Xa:{common_params:{context_params:{experiment_id:c.mendel_ids}},resource:{user_pref:[{key:"Promotion__"+c.pid+"__Viewed",value:a.o.promo}],helpcenter:c.hc,key_type:a.o.st}}})};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var promo='AW_GMB_CS';var st=1;window['sc_trackPromotion']({'promo':promo,'st':st
});})();</script>    <script data-id="fixed_sidebar" nonce="+QS39bNwVq7uhiMgdJyo">function zp(a,b,c){this.S=a;this.o=b;this.V=c||771;this.R=0;Ap(this)}
function Ap(a){var b=document.querySelector(".gaiabar header, .one-google-bar-placeholder");b&&(a.R=b.offsetHeight);Bp(a);Cp(a);window.addEventListener("resize",function(){window.innerWidth>=a.V&&Bp(a);Cp(a)});var c=window.pageYOffset;window.addEventListener("scroll",function(){var b=window.pageYOffset;(c<a.w&&b>=a.w||c>=a.w&&b<a.w)&&Cp(a);c=b})}
function Bp(a){var b=a.S.getBoundingClientRect();a.H=window.pageYOffset+b.top;a.T=document.body.scrollHeight-(a.H+a.S.offsetHeight);a.w=Math.max(a.H-a.R,a.H+a.o.offsetHeight+a.T-window.innerHeight);a.S.style.minHeight=a.o.offsetHeight+"px";a.o.style.left=b.left+"px"}
function Cp(a){var b=window.pageYOffset>=a.w&&window.innerWidth>=a.V;"fixed"==a.o.style.position!=b&&(a.o.style.position=b?"fixed":"static",b&&(a.o.style.top=Math.min(window.innerHeight-a.o.offsetHeight-a.T,a.R)+"px"))}
;</script>   <script data-id="nav_panel" nonce="+QS39bNwVq7uhiMgdJyo">function ps(){this.o=window.sc_scope||document;qs(this)}
function qs(a){for(var b=a.o.getElementsByClassName("sibling-link--has-children"),c=0;c<b.length;c++)b[c].addEventListener("click",function(a){x(a.target,"sibling-link--show-children")});"true"==I("fixed-sidebar-required")&&new zp(a.o.querySelector(".side-container"),a.o.querySelector(".fixed-sidebar-container"),976)}
window.sc_initNavPanel=function(){new ps};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">window['sc_initNavPanel']();</script>       <script data-id="article_survey" nonce="+QS39bNwVq7uhiMgdJyo">function wi(a,b){this.o=a;this.w=b;this.V=this.o.querySelector(".title");this.ha=this.o.querySelector(".how-improve");this.H=-1;this.S=!0;this.T=0;a=this.o.querySelectorAll(".as-button, .as-icon");for(b=0;b<a.length;b++)a[b].addEventListener("click",this.ma.bind(this,a[b]));this.o.querySelector(".submit-button").addEventListener("click",this.R.bind(this,!0));this.w.popup&&xi(this)}
function xi(a){document.addEventListener("scroll",function(b,c){var d;return function(){if(!d){for(var e=Array(arguments.length),f=0;f<arguments.length;f++)e[f]=arguments[f];d=setTimeout(function(){d=null;b.apply(a,e)},c)}}}(a.ka,100).bind(a));a.o.querySelector(".as .dismiss").addEventListener("click",a.W.bind(a,!0))}
wi.prototype.ka=function(){0<window.pageYOffset&&this.S?this.S=!1:(this.S=!1,this.T&&clearTimeout(this.T),this.T=setTimeout(function(){x(this.o.parentElement,"show",!0);window.sc_trackStatsEvent(nb,Kb);setTimeout(function(){this.W(!1)}.bind(this),this.w.popup_ttl)}.bind(this),this.w.popup_delay))};wi.prototype.ma=function(a){this.H=parseInt(a.getAttribute("data-value"),10);this.w.popup?(this.R(!0),x(this.o.parentElement,"show",!1)):(x(this.o,"rated",!0),window.sc_trackStatsEvent(nb,Ob,this.H.toString()),4>this.H?(this.R(!1),this.V.textContent=this.w.response_bad,this.ha.style.display="block",this.o.querySelector("textarea").focus()):this.R(!0))};wi.prototype.W=function(a){x(this.o.parentElement,"show",!1);window.sc_trackStatsEvent(nb,a?Pb:Lb)};wi.prototype.R=function(a){if(!y(this.o,"submitted")){for(var b=[],c=this.o.querySelectorAll('input[type="checkbox"], textarea'),d=0;d<c.length;d++){var e=c[d];if(!1!==e.checked){var f={name:e.name,value:e.value};e.checked&&(f.description=e.nextElementSibling.textContent);b.push(f)}}B({httpMethod:"POST",endpoint:"articlesurvey",Xa:{field:b,rating:this.H.toString(),answer_id:A().pid,metadata:{visit_id:A().visit_id}},params:{current_url:Wa()}});a&&(x(this.o,"submitted",!0),this.V.setAttribute("aria-live","polite"),this.V.textContent=this.w.completed_text,this.ha.style.display="none");B({httpMethod:"POST",endpoint:"cufz",Xa:{success:!0,page_view_id:A().pvid}});window.sc_trackStatsEvent(nb,Zb,this.H.toString())}};window.sc_initArticleSurvey=function(a){var b=(window.sc_scope||document).querySelector(".as");b&&new wi(b,a)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">window['_model']= {};</script> <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var response_good='';var query_good='';var response_bad='Sorry about that';var query_bad='How can we improve it?';var completed_text='Thanks for your feedback!';var popup=false;var popup_delay=3000;var popup_ttl=5000;(function(m){m['response_good']= response_good;m['query_good']= query_good;m['response_bad']= response_bad;m['query_bad']= query_bad;m['completed_text']= completed_text;m['popup']= popup;m['popup_delay']= popup_delay;m['popup_ttl']= popup_ttl;})(window['_model']);})();</script> <script nonce="+QS39bNwVq7uhiMgdJyo">window['sc_initArticleSurvey'](window['_model']);</script>     <script data-id="chat_support" nonce="+QS39bNwVq7uhiMgdJyo">function Ki(a){if(Error.captureStackTrace)Error.captureStackTrace(this,Ki);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}
w(Ki,Error);Ki.prototype.name="CustomError";function Li(a,b){for(var c in a)b.call(void 0,a[c],c,a)}
var Mi={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Ni(a,b){Li(b,function(b,d){b&&b.yb&&(b=b.kb());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Mi.hasOwnProperty(d)?a.setAttribute(Mi[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
function Oi(a){a=a||{};this.operatorDeferredUrl=a.operatorDeferredUrl;this.alphaTestMode=a.alphaTestMode||!1;this.stagingMode=a.stagingMode||!1;this.rosterId=a.rosterId||"talk_roster";this.feedbackId=a.feedbackId||74772;this.moleVersion=a.moleVersion||void 0;this.moleUrl=a.moleUrl||"https://support.google.com/inapp/rts_frame";this.gstaticBaseUrl=a.gstaticBaseUrl||void 0;this.operatorDeferredBaseUrl=a.operatorDeferredBaseUrl||void 0;this.isRtl=a.isRtl||void 0;this.forceLeftMoles=a.forceLeftMoles||
void 0;this.helpCenterName=a.helpCenterName||null;this.localeName=a.localeName||null;this.document=a.document||document;this.source=a.source||void 0;this.entityId=a.entityId||void 0;this.authUser=a.authUser||void 0;this.appDomain=a.appDomain||void 0;this.apiKey=a.apiKey||void 0;this.hideQueueWidget=a.hideQueueWidget||!1;this.enableMinimizeRestoreKeyboardShortcut=a.enableMinimizeRestoreKeyboardShortcut||!1;this.showSecondsInChatTranscript=a.showSecondsInChatTranscript||!1;this.o=a.experiments||void 0}
;function Pi(a,b){this.H=a;this.R=b;this.w=0;this.o=null}
Pi.prototype.get=function(){if(0<this.w){this.w--;var a=this.o;this.o=a.next;a.next=null}else a=this.H();return a};function Qi(a,b){a.R(b);100>a.w&&(a.w++,b.next=a.o,a.o=b)}
;function Ri(a){r.setTimeout(function(){throw a;},0)}
var Si;function Ti(){var a=r.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!H("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;a=t(function(a){if(("*"==d||a.origin==d)&&a.data==
c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Cc()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(va(c.next)){c=c.next;var a=c.cb;c.cb=null;a()}};return function(a){d.next={cb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?function(a){var b=document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){r.setTimeout(a,0)}}
;function Ui(){this.w=this.o=null}
var Wi=new Pi(function(){return new Vi},function(a){a.reset()});Ui.prototype.add=function(a,b){var c=Wi.get();c.set(a,b);this.w?this.w.next=c:this.o=c;this.w=c};Ui.prototype.remove=function(){var a=null;this.o&&(a=this.o,this.o=this.o.next,this.o||(this.w=null),a.next=null);return a};function Vi(){this.next=this.scope=this.o=null}
Vi.prototype.set=function(a,b){this.o=a;this.scope=b;this.next=null};Vi.prototype.reset=function(){this.next=this.scope=this.o=null};function Xi(a,b){Yi||Zi();$i||(Yi(),$i=!0);aj.add(a,b)}
var Yi;function Zi(){if(-1!=String(r.Promise).indexOf("[native code]")){var a=r.Promise.resolve(void 0);Yi=function(){a.then(bj)}}else Yi=function(){var a=bj;!Ca(r.setImmediate)||r.Window&&r.Window.prototype&&!H("Edge")&&r.Window.prototype.setImmediate==r.setImmediate?(Si||(Si=Ti()),Si(a)):r.setImmediate(a)}}
var $i=!1,aj=new Ui;function bj(){for(var a;a=aj.remove();){try{a.o.call(a.scope)}catch(b){Ri(b)}Qi(Wi,a)}$i=!1}
;function cj(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}
function dj(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}}
;function ej(a,b){this.o=0;this.V=void 0;this.R=this.w=this.H=null;this.S=this.T=!1;if(a!=za)try{var c=this;a.call(b,function(a){fj(c,2,a)},function(a){fj(c,3,a)})}catch(d){fj(this,3,d)}}
function gj(){this.next=this.context=this.w=this.H=this.o=null;this.R=!1}
gj.prototype.reset=function(){this.context=this.w=this.H=this.o=null;this.R=!1};var hj=new Pi(function(){return new gj},function(a){a.reset()});function ij(a,b,c){var d=hj.get();d.H=a;d.w=b;d.context=c;return d}
function jj(a){if(a instanceof ej)return a;var b=new ej(za);fj(b,2,a);return b}
ej.prototype.then=function(a,b,c){return kj(this,Ca(a)?a:null,Ca(b)?b:null,c)};cj(ej);function lj(a,b){return kj(a,null,b,void 0)}
ej.prototype.cancel=function(a){0==this.o&&Xi(function(){var b=new mj(a);nj(this,b)},this)};function nj(a,b){if(0==a.o)if(a.H){var c=a.H;if(c.w){for(var d=0,e=null,f=null,g=c.w;g&&(g.R||(d++,g.o==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.o&&1==d?nj(c,b):(f?(d=f,d.next==c.R&&(c.R=d),d.next=d.next.next):oj(c),pj(c,e,3,b)))}a.H=null}else fj(a,3,b)}
function qj(a,b){a.w||2!=a.o&&3!=a.o||rj(a);a.R?a.R.next=b:a.w=b;a.R=b}
function kj(a,b,c,d){var e=ij(null,null,null);e.o=new ej(function(a,g){e.H=b?function(c){try{var e=b.call(d,c);a(e)}catch(n){g(n)}}:a;e.w=c?function(b){try{var e=c.call(d,b);!va(e)&&b instanceof mj?g(b):a(e)}catch(n){g(n)}}:g});e.o.H=a;qj(a,e);return e.o}
ej.prototype.ha=function(a){this.o=0;fj(this,2,a)};ej.prototype.ka=function(a){this.o=0;fj(this,3,a)};function fj(a,b,c){if(0==a.o){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.o=1;a:{var d=c,e=a.ha,f=a.ka;if(d instanceof ej){qj(d,ij(e||za,f||null,a));var g=!0}else if(dj(d))d.then(e,f,a),g=!0;else{if(Da(d))try{var l=d.then;if(Ca(l)){sj(d,l,e,f,a);g=!0;break a}}catch(m){f.call(a,m);g=!0;break a}g=!1}}g||(a.V=c,a.o=b,a.H=null,rj(a),3!=b||c instanceof mj||tj(a,c))}}
function sj(a,b,c,d,e){function f(a){l||(l=!0,d.call(e,a))}
function g(a){l||(l=!0,c.call(e,a))}
var l=!1;try{b.call(a,g,f)}catch(m){f(m)}}
function rj(a){a.T||(a.T=!0,Xi(a.W,a))}
function oj(a){var b=null;a.w&&(b=a.w,a.w=b.next,b.next=null);a.w||(a.R=null);return b}
ej.prototype.W=function(){for(var a;a=oj(this);)pj(this,a,this.o,this.V);this.T=!1};function pj(a,b,c,d){if(3==c&&b.w&&!b.R)for(;a&&a.S;a=a.H)a.S=!1;if(b.o)b.o.H=null,uj(b,c,d);else try{b.R?b.H.call(b.context):uj(b,c,d)}catch(e){vj.call(null,e)}Qi(hj,b)}
function uj(a,b,c){2==b?a.H.call(a.context,c):a.w&&a.w.call(a.context,c)}
function tj(a,b){a.S=!0;Xi(function(){a.S&&vj.call(null,b)})}
var vj=Ri;function mj(a){Ki.call(this,a)}
w(mj,Ki);mj.prototype.name="cancel";
function wj(a,b){this.S=[];this.ra=a;this.ma=b||null;this.R=this.o=!1;this.H=void 0;this.ha=this.ta=this.V=!1;this.T=0;this.w=null;this.W=0}
wj.prototype.cancel=function(a){if(this.o)this.H instanceof wj&&this.H.cancel();else{if(this.w){var b=this.w;delete this.w;a?b.cancel(a):(b.W--,0>=b.W&&b.cancel())}this.ra?this.ra.call(this.ma,this):this.ha=!0;this.o||(a=new xj(this),yj(this),zj(this,!1,a))}};wj.prototype.ka=function(a,b){this.V=!1;zj(this,a,b)};function zj(a,b,c){a.o=!0;a.H=c;a.R=!b;Aj(a)}
function yj(a){if(a.o){if(!a.ha)throw new Bj(a);a.ha=!1}}
wj.prototype.callback=function(a){yj(this);zj(this,!0,a)};function Cj(a,b,c){a.S.push([b,c,void 0]);a.o&&Aj(a)}
wj.prototype.then=function(a,b,c){var d,e,f=new ej(function(a,b){d=a;e=b});Cj(this,d,function(a){a instanceof xj?f.cancel():e(a)});return f.then(a,b,c)};cj(wj);function Dj(a){return qc(a.S,function(a){return Ca(a[1])})}
function Aj(a){if(a.T&&a.o&&Dj(a)){var b=a.T,c=Ej[b];c&&(r.clearTimeout(c.o),delete Ej[b]);a.T=0}a.w&&(a.w.W--,delete a.w);b=a.H;for(var d=c=!1;a.S.length&&!a.V;){var e=a.S.shift(),f=e[0],g=e[1];e=e[2];if(f=a.R?g:f)try{var l=f.call(e||a.ma,b);va(l)&&(a.R=a.R&&(l==b||l instanceof Error),a.H=b=l);if(dj(b)||"function"===typeof r.Promise&&b instanceof r.Promise)d=!0,a.V=!0}catch(m){b=m,a.R=!0,Dj(a)||(c=!0)}}a.H=b;d&&(l=t(a.ka,a,!0),d=t(a.ka,a,!1),b instanceof wj?(Cj(b,l,d),b.ta=!0):b.then(l,d));c&&(b=
new Fj(b),Ej[b.o]=b,a.T=b.o)}
function Bj(){Ki.call(this)}
w(Bj,Ki);Bj.prototype.message="Deferred has already fired";Bj.prototype.name="AlreadyCalledError";function xj(){Ki.call(this)}
w(xj,Ki);xj.prototype.message="Deferred was canceled";xj.prototype.name="CanceledError";function Fj(a){this.o=r.setTimeout(t(this.H,this),0);this.w=a}
Fj.prototype.H=function(){delete Ej[this.o];throw this.w;};var Ej={};function Gj(a,b){var c=b||{};b=c.document||document;var d=ed(a),e=td(),f={yg:e,Vg:void 0},g=new wj(Hj,f),l=null,m=null!=c.timeout?c.timeout:5E3;0<m&&(l=window.setTimeout(function(){Ij(e,!0);var a=new Jj(1,"Timeout reached for loading script "+d);yj(g);zj(g,!1,a)},m),f.Vg=l);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(Ij(e,c.Vm||!1,l),g.callback(null))};e.onerror=function(){Ij(e,!0,l);var a=new Jj(0,"Error while loading script "+d);yj(g);zj(g,!1,a)};f=c.attributes||{};Bc(f,{type:"text/javascript",charset:"UTF-8"});Ni(e,f);e.src=ed(a);Kj(b).appendChild(e);return g}
function Kj(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&0!=b.length?b[0]:a.documentElement}
function Hj(){if(this&&this.yg){var a=this.yg;a&&"SCRIPT"==a.tagName&&Ij(a,!0,this.Vg)}}
function Ij(a,b,c){null!=c&&r.clearTimeout(c);a.onload=za;a.onerror=za;a.onreadystatechange=za;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}
function Jj(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);Ki.call(this,c);this.code=a}
w(Jj,Ki);$c("https://apis.google.com/js/client.js?onload=%{onload}");var Lj=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function Mj(){}
;var Nj;function Oj(){}
w(Oj,Mj);Oj.prototype.o=function(){a:{if(!this.w&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var a=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++){var c=a[b];try{new ActiveXObject(c);var d=this.w=c;break a}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}d=this.w}return d?new ActiveXObject(d):new XMLHttpRequest};Nj=new Oj;function Pj(a){var b={Ug:7E3,dh:new Qj};return Rj(a,b).then(function(a){var c=a.responseText;b&&b.Nk&&(a=b.Nk,0==c.lastIndexOf(a,0)&&(c=c.substring(a.length)));return JSON.parse(c)})}
function Rj(a,b){var c=b||{},d=c.dh?c.dh.o():Nj.o();return lj(new ej(function(b,f){var e;try{d.open("GET",a,!0)}catch(n){f(new Sj("Error opening XHR: "+n.message,a,d))}d.onreadystatechange=function(){if(4==d.readyState){r.clearTimeout(e);a:switch(d.status){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}!c&&(c=0===d.status)&&(c=a.match(Lj)[1]||null,!c&&r.self&&r.self.location&&(c=r.self.location.protocol,c=c.substr(0,c.length-1)),c=c?c.toLowerCase():"",c=!("http"==c||"https"==c||""==c));c?b(d):f(new Tj(d.status,a,d))}};d.onerror=function(){f(new Sj("Network error",a,d))};if(c.headers)for(var l in c.headers){var m=c.headers[l];null!=m&&d.setRequestHeader(l,m)}c.withCredentials&&(d.withCredentials=c.withCredentials);c.responseType&&(d.responseType=c.responseType);c.mimeType&&d.overrideMimeType(c.mimeType);0<c.Ug&&(e=r.setTimeout(function(){d.onreadystatechange=za;d.abort();f(new Uj(a,d))},c.Ug));try{d.send(null)}catch(n){d.onreadystatechange=za,r.clearTimeout(e),f(new Sj("Error sending XHR: "+n.message,a,d))}}),function(a){a instanceof mj&&d.abort();throw a;})}
function Sj(a,b){Ki.call(this,a+", url="+b);this.url=b}
w(Sj,Ki);Sj.prototype.name="XhrError";function Tj(a,b,c){Sj.call(this,"Request Failed, status="+a,b,c);this.status=a}
w(Tj,Sj);Tj.prototype.name="XhrHttpError";function Uj(a,b){Sj.call(this,"Request timed out",a,b)}
w(Uj,Sj);Uj.prototype.name="XhrTimeoutError";function Qj(){}
w(Qj,Mj);Qj.prototype.o=function(){var a=new XMLHttpRequest;if("withCredentials"in a)return a;if("undefined"!=typeof XDomainRequest)return new Vj;throw Error("Unsupported browser");};function Vj(){this.o=new XDomainRequest;this.readyState=0;this.onreadystatechange=null;this.responseText="";this.status=-1;this.statusText="";this.o.onload=t(this.Gi,this);this.o.onerror=t(this.If,this);this.o.onprogress=t(this.Hi,this);this.o.ontimeout=t(this.Ii,this)}
p=Vj.prototype;p.open=function(a,b,c){if(null!=c&&!c)throw Error("Only async requests are supported.");this.o.open(a,b)};p.send=function(a){if(a)if("string"==typeof a)this.o.send(a);else throw Error("Only string data is supported");else this.o.send()};p.abort=function(){this.o.abort()};p.setRequestHeader=h();p.getResponseHeader=function(a){return"content-type"==a.toLowerCase()?this.o.contentType:""};p.Gi=function(){this.status=200;this.responseText=this.o.responseText;Wj(this,4)};p.If=function(){this.status=500;this.responseText="";Wj(this,4)};p.Ii=function(){this.If()};p.Hi=function(){this.status=200;Wj(this,1)};function Wj(a,b){a.readyState=b;if(a.onreadystatechange)a.onreadystatechange()}
;function Xj(a){this.o=a instanceof Oi?a:new Oi(a);this.o=Yj(this.o);this.w=Zj(this);this.o.moleVersion||this.w.then(function(a){this.o.moleVersion=a.cbfVersion},h(),this);this.o.o||this.w.then(function(a){this.o.o=a.experiments},h(),this);this.w.then(this.R,h(),this)}
function ak(){return ya("cs.operatorDeferredInstance")}
function bk(){var a=ya("cs.operatorDeferredPromise");return a instanceof ej?a:null!=a?jj(a):null}
function ck(a){v("cs.operatorDeferredPromise",a)}
function dk(){}
function Yj(a){var b={},c;for(c in a)b[c]=a[c];b.document=b.document||document;null!=b.localeName&&(b.localeName=b.localeName.replace(/_/g,"-"));b.localeName=b.localeName&&0<=mc(ek,b.localeName)?b.localeName:"en";b.helpCenterName=b.helpCenterName||"chatsupport";b.apiKey=b.apiKey||"AIzaSyB5V4SIBGmrqREm7kf2fBJgPcBMCdUrLzE";return b}
function Zj(a){return Pj(a.o.alphaTestMode?"//ssl.gstatic.com/support/realtime/operatorParamsDev":a.o.stagingMode?"//ssl.gstatic.com/support/realtime/operatorParamsStaging":"//ssl.gstatic.com/support/realtime/operatorParams").then(function(a){if(!a)throw Error("operatorParams is null");return a},function(a){throw a;})}
function fk(a){var b=bk();if(b)return b;if(b=ak())return a=jj(b),ck(a),a;a=gk(a).then(function(a){var b={document:this.o.document};this.o.operatorDeferredUrl=a;return Gj(ud(a),b).then(function(){return r.cs.OperatorDeferred.getInstance(this.o)},null,this)},null,a);ck(a);return a}
Xj.prototype.R=function(a){(new RegExp(a.eagerLoadHostnamePattern,a.eagerLoadHostnameFlags)).test(this.o.document.location.href)&&lj(fk(this),Ga(dk,"Error retrieving OperatorDeferred"))};function gk(a){return a.o.operatorDeferredUrl?jj(a.o.operatorDeferredUrl):a.o.operatorDeferredBaseUrl?(a=a.o.operatorDeferredBaseUrl+"/"+a.o.moleVersion+"/operatordeferred_bin_base__"+a.o.localeName.replace(/-/g,"_").toLowerCase()+".js",jj(a)):a.w.then(t(function(a){return"https://ssl.gstatic.com/support/realtime/operator/"+a.cbfVersion+"/operatordeferred_bin_base__"+this.o.localeName.replace(/-/g,"_").toLowerCase()+".js"},a),h())}
function hk(a,b){fk(a).then(Ga(function(a,b){b.registerAvailabilityCallbacks(a)},b))}
Xj.prototype.H=function(){return fk(this).then(function(a){a.getAvailabilities()})};function ik(a,b,c,d){b=Ga(function(a,b,c,d,m,n){return n.requestSupport(a,b,c,d,m)},b,c,void 0,!0,d);return(c=ak())?(a=b(c),jj(a)):fk(a).then(b)}
var ek="ar ar-XB bg ca cs da de el en en-AU en-GB en-XA en-XC es es-419 et fa fi fil fr hi hr hu id it iw ja ko lt lv ms nl no pl pt-PT pt-BR ro ru sk sl sr sv th tr uk vi zh-CN zh-TW zh-HK".split(" ");function jk(a){this.o=new Xj({helpCenterName:A().hc,localeName:a.lang,isRtl:A().rtl,alphaTestMode:1==Oa("hcfe.page.Page.model.chatAlphaTestMode"),stagingMode:1==Oa("hcfe.page.Page.model.chatStagingMode")||"PROD"!=a.env,rosterId:"chat-support-roster",source:3,authUser:A().au||0});a=document.createElement("div");a.id="chat-support-roster";a.style.display="none";document.body.appendChild(a)}
jk.prototype.R=function(a){hk(this.o,a);"dap"!=Oa("test")&&(this.o.H(),kk(this))};function kk(a){a.w||(a.w=window.setInterval(a.o.H.bind(a.o),3E4),document.addEventListener("pjaxunload",function(){window.clearInterval(this.w)}.bind(a)))}
jk.prototype.H=function(a,b,c,d){ik(this.o,a,b,c).then(function(){window.sc_trackStatsEvent(yb,Vb);d&&d()})};window.sc_initChatSupport=function(a){if(!window.sc_registerChatPools||window.sc_refresh)a=new jk(a),window.sc_registerChatPools=a.R.bind(a),window.sc_requestChatSupport=a.H.bind(a)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var env='PROD';var lang='en';window['sc_initChatSupport']({'env':env,'lang':lang
});})();</script>                     <script data-id="video" nonce="+QS39bNwVq7uhiMgdJyo">var hp=fd(Zc($c("//www.youtube.com/player_api"))),ip=[],jp=!1;function kp(){if(!jp){window.onYouTubeIframeAPIReady=lp;var a=td();a.src=ed(hp);document.head.appendChild(a);jp=!0}}
function lp(){for(;0<ip.length;)ip.shift()()}
function mp(a,b,c,d){switch(a){case -1:a=Xb;break;case 0:a=Wb;break;case 1:a=bc;break;case 2:a=cc;break;case 3:a=dc;break;case 5:a=ec;break;default:a=Gb}window.sc_trackStatsEvent(xb,a,b,c+","+d)}
;</script>      <script data-id="inline_video" nonce="+QS39bNwVq7uhiMgdJyo">function Xp(a){this.o=a;Yp(this)}
var Zp=16/9;function $p(a){window.YT&&window.YT.Player?new Xp(a):ip.push(function(a){new Xp(a)}.bind(void 0,a))}
function Yp(a){var b=document.createElement("span");b.className="embedded-video--close-link";b.style.display="none";b.setAttribute("role","button");b.setAttribute("aria-label",fe.close);b.addEventListener("click",function(){c.stopVideo()});a.o.parentNode.insertBefore(b,a.o);var c=new window.YT.Player(a.o,{width:400,height:230,videoId:a.o.getAttribute("data-videoid"),playerVars:{cc_load_policy:1,controls:2,rel:0,hl:window.sc_pageModel.lang},events:{onReady:function(){c.getIframe().focus()},onStateChange:function(a){var d=c.getIframe();switch(a.data){case 1:d.style.width="100%";d.style.height=d.offsetWidth/Zp+"px";b.style.display="block";break;case -1:case 0:d.style.width="400px",d.style.height="230px",b.style.display="none"}d=c.getCurrentTime();var f=c.getDuration();mp(a.data,this.o.getAttribute("data-videoid"),d,f)}.bind(a)}})}
window.sc_initInlineVideos=function(a){if(a){a=(window.sc_scope||document).querySelectorAll(".embedded-video, .embedded-video-custom, .embedded-video-large");for(var b=0;b<a.length;b++){var c=document.createElement("div");c.className="embedded-video-large";c.setAttribute("data-videoid",a[b].getAttribute("data-videoid"));c.style.width="400px";c.style.height="230px";a[b].parentNode.replaceChild(c,a[b]);c.style.backgroundImage="url(//i.ytimg.com/vi/"+c.getAttribute("data-videoid")+"/hqdefault.jpg)";var d=document.createElementNS("http://www.w3.org/2000/svg","svg");d.setAttribute("viewBox","0 0 48 48");var e=document.createElementNS("http://www.w3.org/2000/svg","path");e.setAttribute("d","M40 8.8c-1.2-.4-8.6-.8-16-.8s-14.8.4-16 .8c-3.1 1-4 8-4 15.2s.9 14.2 4 15.2c1.2.4 8.6.8 16 .8s14.8-.4 16-.8c3.1-1 4-8 4-15.2s-.9-14.2-4-15.2zM20 33V15l12 9-12 9z");d.appendChild(e);e=document.createElement("button");e.setAttribute("aria-label",fe.loadVideo);e.setAttribute("aria-haspopup","true");e.addEventListener("click",$p.bind(void 0,c,!0));d.appendChild(e);c.appendChild(d);c.addEventListener("click",$p.bind(void 0,c,!0))}kp()}else{a=(window.sc_scope||document).getElementsByClassName("embedded-video-large");for(b=0;b<a.length;b++)$p(a[b],!1);window.YT&&window.YT.Player||kp()}};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var is_mobile=false;var close_dialog='Close';var load_video='Load video';hcfe.Page.setString('close',close_dialog);hcfe.Page.setString('loadVideo',load_video);window['sc_initInlineVideos'](is_mobile);})();</script>    <script data-id="community" nonce="+QS39bNwVq7uhiMgdJyo">function pk(a){var b=window.sc_scope;this.w=a;this.H=b||document;this.o=null;this.o=this.H.getElementsByClassName("related-item--community");0!=this.o.length&&qk(this)}
function qk(a){var b=new XMLHttpRequest;b.addEventListener("load",function(){try{var a=JSON.parse(b.responseText).response.messages.message}catch(g){}if(a){Array.isArray(a)||(a=[a]);for(var d=0;d<a.length;d++){var e=a[d],f=this.o[d];f.querySelector("strong").textContent=e.author.login.$;f=f.querySelector("a");f.href=e.view_href;f.textContent=e.subject.$}}}.bind(a));b.open("GET",a.w.url+"/restapi/vc/search/messages?page=1&page_size="+a.o.length+"&q="+encodeURIComponent(a.w.query)+"&restapi.response_style=view&search_type=thread&solved=true&xslt=json.xsl");b.send()}
window.sc_initCommunity=function(a){new pk(a)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var url='https://www.en.advertisercommunity.com/';var query='Create and manage more than one campaign';window['sc_initCommunity']({'url':url,'query':query
});})();</script>    <script data-id="glossary" nonce="+QS39bNwVq7uhiMgdJyo">function Yk(a,b){this.w=a;this.T=b;this.H=this.o=null;this.R=0;this.S=!1;Zk(this)}
function Zk(a){a.o=document.createElement("div");a.o.className="glossary-def";a.H=window.sc_createBubble(a.w,"bottom",a.o,0,12,!1,!1);a.w.addEventListener("mouseenter",function(){$k(this);window.clearTimeout(this.R)}.bind(a));a.o.addEventListener("mouseenter",function(){window.clearTimeout(this.R)}.bind(a));var b=function(){this.R=window.setTimeout(this.H.hide,500)}.bind(a);a.w.addEventListener("mouseleave",b);a.o.addEventListener("mouseleave",b);a.w.setAttribute("data-stats-ve",tb.id)}
function $k(a){a.H.show();if(!a.S){if(window.sc_createSpinner){var b=window.sc_createSpinner();a.o.appendChild(b.getElement())}var c=document.createElement("div"),d=a.w.getAttribute("data-answer");window.sc_renderRequest("ANSWER",d,c,function(){this.o.textContent="";var a=c.querySelector(".glossary-short");a?this.o.appendChild(a):this.o.appendChild(c);a=document.createElement("a");a.href=(A().ehn||"")+"/"+A().ehc+"/answer/"+d+"?ctx=glossary";a.textContent=this.T.learn_more;this.o.appendChild(a);this.H.position()}.bind(a));a.S=!0;window.sc_trackStatsEvent(tb,Kb,d)}}
window.sc_initGlossary=function(a){for(var b=(window.sc_scope||document).getElementsByClassName("glossary-term"),c=0;c<b.length;c++)new Yk(b[c],a)};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var learn_more='Read more';window['sc_initGlossary']({'learn_more':learn_more
});})();</script>      <script data-id="select" nonce="+QS39bNwVq7uhiMgdJyo">var lo=1;function mo(a){this.w=a;this.o=this.W=this.H=null;this.R=[];this.S=-1;this.ra=this.td.bind(this);this.ka=this.se.bind(this);this.ta=this.ha=this.V=0;this.T=!1;this.ma=0;no(this)}
function no(a){a.H=document.createElement("div");a.H.className=a.w.className;var b=a.w.getAttribute("aria-label");b&&a.H.setAttribute("aria-label",b);x(a.H,"sc-select",!0);a.H.setAttribute("tabindex",0);a.H.setAttribute("role","listbox");a.H.addEventListener("mousedown",function(a){y(this.o,"sc-select-show")?a.target==this.o||this.o.contains(a.target)||this.td():0==a.button&&oo(this)}.bind(a));a.H.addEventListener("keydown",a.Ej.bind(a));a.W=document.createElement("span");a.H.appendChild(a.W);b=document.createElementNS("http://www.w3.org/2000/svg","svg");b.setAttribute("viewBox","0 0 8 12");var c=document.createElementNS("http://www.w3.org/2000/svg","path");c.setAttribute("d","M0 5l4-4 4 4z M0 8l4 4 4-4z");b.appendChild(c);a.H.appendChild(b);a.o=document.createElement("ol");a.o.addEventListener("mousemove",function(){this.T=!0}.bind(a));a.o.addEventListener("scroll",function(){0<this.ma?this.ma--:this.se()}.bind(a));a.H.appendChild(a.o);a.Tf();a.w.addEventListener("optionschange",a.Tf.bind(a));a.w.addEventListener("change",function(){this.W.textContent=this.w.options[this.w.selectedIndex].text;this.H.setAttribute("aria-activedescendant",this.R[this.w.selectedIndex].id)}.bind(a));a.w.style.display="none";a.w.nextElementSibling?a.w.parentNode.insertBefore(a.H,a.w.nextElementSibling):a.w.parentNode.appendChild(a.H)}
p=mo.prototype;p.Tf=function(){this.o.textContent="";this.o.style.height="";this.ha=0;this.R=[];for(var a=0;a<this.w.options.length;a++){var b=document.createElement("li");b.setAttribute("role","option");b.id=":"+lo++;b.textContent=this.w.options[a].text;b.addEventListener("mouseup",function(a){this.T&&this.xe(a)}.bind(this,a));b.addEventListener("click",this.xe.bind(this,a));b.addEventListener("mouseenter",function(a){this.T&&po(this,a)}.bind(this,a));b.addEventListener("mouseleave",function(a){this.T&&this.S==a&&(this.S=-1,x(this.R[a],"sc-select-highlight",!1))}.bind(this,a));this.R.push(b);this.o.appendChild(b)}-1!=this.w.selectedIndex&&(this.W.textContent=this.w.options[this.w.selectedIndex].text,this.H.setAttribute("aria-activedescendant",this.R[this.w.selectedIndex].id))};function oo(a){a.T=!1;po(a,a.w.selectedIndex);a.se();document.addEventListener("click",a.ra);document.addEventListener("scroll",a.ka);window.addEventListener("resize",a.ka);cb(!0)}
p.td=function(a){if(!a||a.target!=this.H&&!this.H.contains(a.target)&&a.target!=this.w)document.removeEventListener("click",this.ra),document.removeEventListener("scroll",this.ka),window.removeEventListener("resize",this.ka),x(this.o,"sc-select-show",!1),cb(!1)};p.se=function(){var a,b;if(y(this.o,"sc-select-show"))this.V=this.o.offsetTop-this.o.scrollTop;else{x(this.o,"sc-select-show",!0);var c=this.R[0]?this.R[0].offsetHeight:0;this.V=this.H.offsetHeight/2-c/2-c*this.w.selectedIndex-(this.R[0]?this.R[0].offsetTop:0);this.ha||(this.ha=this.o.offsetHeight,this.ta=this.o.offsetHeight-c*this.R.length)}c=b=0;var d=this.o.offsetParent;for(a=!1;d;)b-=d.offsetLeft,c-=d.offsetTop,"fixed"==window.getComputedStyle(d).position&&(a=!0),d=d.offsetParent;a||(b+=window.pageXOffset,c+=window.pageYOffset);d=b;a=document.documentElement.clientWidth;b=document.documentElement.clientHeight;d=Math.max(Math.min(A().rtl?this.H.offsetWidth-this.o.offsetWidth:0,d+a-this.o.offsetWidth),d);a=Math.max(this.V,c);c=Math.min(this.V+this.ha,c+b)-a;c<=this.ta||(this.o.style.left=d+"px",this.o.style.top=a+"px",this.o.style.height=c+"px",c=a-this.V,this.o.scrollTop!=c&&(this.ma++,this.o.scrollTop=c))};p.xe=function(a){var b=this.w.options[a];b.selected||(b.selected=!0,this.W.textContent=b.text,this.H.setAttribute("aria-activedescendant",this.R[a].id),C(this.w,"change"));C(b,"click");this.td()};function po(a,b){-1!=a.S&&x(a.R[a.S],"sc-select-highlight",!1);a.S=b;x(a.R[a.S],"sc-select-highlight",!0)}
p.Ej=function(a){switch(a.which){case 13:case 32:y(this.o,"sc-select-show")?-1!=this.S&&this.xe(this.S):oo(this);break;case 27:this.td();this.H.setAttribute("aria-activedescendant",this.R[this.w.selectedIndex].id);break;case 38:a.preventDefault();y(this.o,"sc-select-show")||oo(this);a=-1==this.S?0:(this.S-1+this.R.length)%this.R.length;po(this,a);this.H.setAttribute("aria-activedescendant",this.R[a].id);qo(this);break;case 40:a.preventDefault(),y(this.o,"sc-select-show")||oo(this),a=-1==this.S?0:(this.S+1)%this.R.length,po(this,a),this.H.setAttribute("aria-activedescendant",this.R[a].id),qo(this)}};function qo(a){if(-1!=a.S){var b=a.R[a.S];b.offsetTop<a.o.scrollTop?(a.T=!1,a.o.scrollTop=b.offsetTop):b.offsetTop+b.offsetHeight>a.o.scrollTop+a.o.offsetHeight&&(a.T=!1,a.o.scrollTop=b.offsetTop+b.offsetHeight-a.o.offsetHeight)}}
window.sc_initSelects=function(){for(var a=(window.sc_scope||document).getElementsByTagName("select"),b=0;b<a.length;b++)new mo(a[b])};</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">window['sc_initSelects']();</script>         <script data-id="social_button" nonce="+QS39bNwVq7uhiMgdJyo">v("hcfe.SocialButton.setUpAll",function(){for(var a={},b=q(F().querySelectorAll(".social-widget")),c=b.next();!c.done;a={url:a.url},c=b.next())c=c.value,a.url=c.getAttribute("data-url"),a.url&&c.addEventListener("click",function(a){return function(){window.open(a.url,"","menubar=no,toolbar=no,scrollbars=yes,resizable=yes,height=600,width=600")}}(a))});</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">hcfe.SocialButton.setUpAll();</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">(function(){var rid='default';if (rid && typeof window[rid]=== 'function'){window[rid]({'getChild':function(){}});}
})();</script>  <script data-id="keyboard_focus" nonce="+QS39bNwVq7uhiMgdJyo">function Ym(){var a=!1;document.addEventListener("keydown",function(){return a=!0});document.addEventListener("mousedown",function(){return a=!1});document.addEventListener("focusin",function(b){return x(b.target,"keyboard-focus",a)});document.addEventListener("focusout",function(a){return x(a.target,"keyboard-focus",!1)})}
function Zm(){$m||($m=new Ym)}
v("module$exports$hcfe$KeyboardFocus.setUp",Zm);var $m;v("hcfe.KeyboardFocus.setUp",Zm);</script>  <script nonce="+QS39bNwVq7uhiMgdJyo">hcfe.KeyboardFocus.setUp();</script>  <script data-id="accessibility" nonce="+QS39bNwVq7uhiMgdJyo">v("hcfe.Accessibility",function(){for(var a=F().querySelectorAll(".alert"),b=0;b<a.length;b++)a[b].setAttribute("role","alert")});</script> 
