Function.prototype.bind||(Function.prototype.bind=function(a){function b(){return e.apply(this instanceof c?this:a,d.concat(Array.prototype.slice.call(arguments)))}
function c(){}
if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var d=Array.prototype.slice.call(arguments,1),e=this;c.prototype=this.prototype;b.prototype=new c;return b});










Function h(){return function(){}}
function aa(a){return function(b){this[a]=b}}
function k(a){return function(){return this[a]}}
function ba(a){return function(){return a}}
var p,ca=[];function da(a){return function(){return ca[a].apply(this,arguments)}}
var ea="function"==typeof Object.create?Object.create:function(a){function b(){}
b.prototype=a;return new b},fa;if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;function la(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Mc=b.prototype}
var ma="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},na="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function oa(){oa=h();na.Symbol||(na.Symbol=pa)}
var pa=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();function qa(){oa();var a=na.Symbol.iterator;a||(a=na.Symbol.iterator=na.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ma(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ra(this)}});qa=h()}
function ra(a){var b=0;return sa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}
function sa(a){qa();a={next:a};a[na.Symbol.iterator]=function(){return this};return a}
function q(a){qa();var b=a[Symbol.iterator];return b?b.call(a):ra(a)}
function ta(a){if(!(a instanceof Array)){a=q(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function ua(a){if(a){for(var b=na,c=["Promise"],d=0;d<c.length-1;d++){var e=c[d];e in b||(b[e]={});b=b[e]}c=c[c.length-1];d=b[c];a=a(d);a!=d&&null!=a&&ma(b,c,{configurable:!0,writable:!0,value:a})}}
ua(function(a){function b(a){this.o=0;this.H=void 0;this.w=[];var b=this.R();try{a(b.resolve,b.reject)}catch(m){b.reject(m)}}
function c(){this.o=null}
function d(a){return a instanceof b?a:new b(function(b){b(a)})}
if(a)return a;c.prototype.w=function(a){null==this.o&&(this.o=[],this.R());this.o.push(a)};c.prototype.R=function(){var a=this;this.H(function(){a.T()})};var e=na.setTimeout;c.prototype.H=function(a){e(a,0)};c.prototype.T=function(){for(;this.o&&this.o.length;){var a=this.o;this.o=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(n){this.S(n)}}}this.o=null};c.prototype.S=function(a){this.H(function(){throw a;})};b.prototype.R=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}
var b=this,c=!1;return{resolve:a(this.ka),reject:a(this.S)}};b.prototype.ka=function(a){if(a===this)this.S(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.ma(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.ha(a):this.T(a)}};b.prototype.ha=function(a){var b=void 0;try{b=a.then}catch(m){this.S(m);return}"function"==typeof b?this.ra(b,a):this.T(a)};b.prototype.S=function(a){this.V(2,a)};b.prototype.T=function(a){this.V(1,a)};b.prototype.V=function(a,b){if(0!=this.o)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.o);this.o=a;this.H=b;this.W()};b.prototype.W=function(){if(null!=this.w){for(var a=this.w,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.w=null}};var f=new c;b.prototype.ma=function(a){var b=this.R();a.Yc(b.resolve,b.reject)};b.prototype.ra=function(a,b){var c=this.R();try{a.call(b,c.resolve,c.reject)}catch(n){c.reject(n)}};b.prototype.then=function(a,c){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(dd){f(dd)}}:b}
var e,f,g=new b(function(a,b){e=a;f=b});this.Yc(d(a,e),d(c,f));return g};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.Yc=function(a,b){function c(){switch(d.o){case 1:a(d.H);break;case 2:b(d.H);break;default:throw Error("Unexpected state: "+d.o);}}
var d=this;null==this.w?f.w(c):this.w.push(function(){f.w(c)})};b.resolve=d;b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(b,c){for(var e=q(a),f=e.next();!f.done;f=e.next())d(f.value).Yc(b,c)})};b.all=function(a){var c=q(a),e=c.next();return e.done?d([]):new b(function(a,b){function f(b){return function(c){g[b]=c;l--;0==l&&a(g)}}
var g=[],l=0;do g.push(void 0),l++,d(e.value).Yc(f(g.length-1),b),e=c.next();while(!e.done)})};return b});var r=this;function va(a){return void 0!==a}
function wa(a){return"string"==typeof a}
function xa(a){return"number"==typeof a}
function ya(a,b){a=a.split(".");b=b||r;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}
function za(){}
function Aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b}
function Ba(a){return"array"==Aa(a)}
function Ca(a){return"function"==Aa(a)}
function Da(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function Ea(a,b,c){return a.call.apply(a.bind,arguments)}
function Fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}
function t(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?t=Ea:t=Fa;return t.apply(null,arguments)}
function Ga(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}
var Ha=Date.now||function(){return+new Date};function v(a,b){a=a.split(".");var c=r;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&va(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}
function w(a,b){function c(){}
c.prototype=b.prototype;a.Mc=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}}
;var Ia=null,Ja="",Ka="";function x(a,b,c){var d="undefined"==typeof c;if(a.classList)d?a.classList.toggle(b):c?a.classList.add(b):a.classList.remove(b);else{var e=La(a),f=-1!=e.indexOf(b);if(!c&&!d||f)if((!1===c||d)&&f)e=e.filter(function(a){return a!=b});else return;else e.push(b);Ma(a,e.join(" "))}}
function Na(a){return a instanceof SVGElement?a.getAttribute("class")||"":a.className}
function Ma(a,b){a instanceof SVGElement?a.setAttribute("class",b):a.className=b}
function y(a,b){return-1!=Na(a).split(" ").indexOf(b)}
function La(a){return Na(a)?Na(a).split(/\s+/):[]}
function Oa(a,b){return(a=(new RegExp("[?&]"+Pa(encodeURIComponent(a))+"=([^&]*)")).exec(b||A().query))?decodeURIComponent(a[1].replace(/\+/g," ")):""}
function Qa(a,b,c){a=encodeURIComponent(a);b=encodeURIComponent(b);var d=new RegExp("([?&]"+Pa(a)+"=)([^&]*)");return d.test(c)?c.replace(d,"$1"+b.replace("$","$$")):c?c+"&"+a+"="+b:"?"+a+"="+b}
function Ra(a){return(a=(new RegExp("[#&]"+Pa(encodeURIComponent(a))+"=([^&]*)")).exec(window.location.hash))?decodeURIComponent(a[1].replace(/\+/g," ")):""}
function Sa(a,b){a=encodeURIComponent(a);b=encodeURIComponent(b);var c=new RegExp("([#&]"+Pa(a)+"=)([^&]*)");a=c.test(window.location.hash)?window.location.hash.replace(c,"$1"+b.replace("$","$$")):window.location.hash&&"#"!=window.location.hash?window.location.hash+"&"+a+"="+b:"#"+a+"="+b;window.history.replaceState?window.history.replaceState(null,"",a):window.location.replace(a)}
function Ta(a){a=Pa(encodeURIComponent(a));a=new RegExp("(?:(#)|&)"+a+"=[^&]*$|([#&])"+a+"=[^&]*.");a.test(window.location.hash)&&(a=window.location.hash.replace(a,"$1$2"),window.history.replaceState?window.history.replaceState(null,"",a):window.location.replace(a))}
function Pa(a){return a.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")}
function Ua(a,b){var c=0>a.indexOf("?")?"?":"&";(b=b.Sf||A().mendel_ids)&&b.length&&(a+=c+"mendel_ids="+b.join(),c="&");b=A();b.au&&(a+=c+"authuser="+b.au);return a}
function B(a){var b=A(),c=b.ehn+"/"+(a.fe||b.ehc)+"/apis/"+a.endpoint;a.params=a.params||{};a.params.hl=b.lang;a.params.key=a.Hk?b.skey:b.key;a.params.request_source=b.rs;var d=a.ab;a.ab=function(e){var f=e.getResponseHeader("X-SupportContent-XsrfToken");f?(b.xsrf=f,a.ab=d,Va(c,a)):d&&d(e)};var e="",f;for(f in a.params)for(var g=Array.isArray(a.params[f])?a.params[f]:[a.params[f]],l=0;l<g.length;++l)e+=(e?"&":"?")+encodeURIComponent(f)+"="+encodeURIComponent(g[l]);c+=e;c=Ua(c,a);Va(c,a)}
function Va(a,b){var c=b||{},d=new XMLHttpRequest;d.open(c.httpMethod||"GET",a);d.withCredentials=!0;d.setRequestHeader("X-SupportContent-AllowApiCookieAuth","true");(a=A().auth_token)&&d.setRequestHeader("Authorization",a);d.setRequestHeader("X-SupportContent-XsrfToken",A().xsrf);c.Na&&d.addEventListener("load",function(){c.Na(d)});c.ab&&d.addEventListener("error",function(){c.ab(d)});c.Xa?d.send(JSON.stringify(c.Xa)):d.send()}
function Wa(){var a=A(),b=a.bcUrl;a.query&&(b+=a.query);return b+window.location.hash}
function C(a,b,c){var d=document.createEvent("Event");d.initEvent(b,!0,!0);c&&(d.detail=c);a.dispatchEvent(d)}
function Xa(){return 770>=window.innerWidth}
var Ya=[];function E(a){a=Za(a);for(var b=0;b<Ya.length;b++)Ya[b](a);window.location=a.href}
function $a(a){var b=A(),c=/([^/?#]+)/;if(!Ia){Ia=Za(b.bcUrl);var d=Ia.href;Ja=(d=c.exec(d.substring(d.indexOf("//")+2)))?d[1]:"";Ka=(d=c.exec(b.ehn.substring(b.ehn.indexOf("//")+2)))?d[1]:""}a=a.href;b=b?b.legacy_url:null;c=(c=c.exec(a.substring(a.indexOf("//")+2)))?c[1]:"";return(0==a.indexOf("http")||0==a.indexOf("//"))&&(!b||-1==a.indexOf(b))&&c!=Ja&&c!=Ka}
function Za(a){var b=document.createElement("a");b.href=a;return b}
function ab(a){var b=a.indexOf("//");return(a=/(\/[^?#]+)/.exec(a.substring(-1==b?0:b+2)))?a[1]:""}
function bb(a){return(a=/^\/([^/?#]+)/.exec(ab(a.href)))?a[1]:""}
function cb(a){C(document,a?"sc_modalShow":"sc_modalHide")}
function A(){return window.sc_pageModel}
function F(){return window.sc_scope||document}
function db(){var a=document.querySelector("#gb, .fixed-one-bar-placeholder");if(a&&"fixed"==window.getComputedStyle(a).position)return a.offsetHeight}
var eb={id:0,n:"unknown"},fb={id:1,n:"homepage"},gb={id:2,n:"zippy"},hb={id:8,n:"carousel"},ib={id:10,n:"search"},jb={id:11,n:"search results"},kb={id:13,n:"proactive chat"},lb={id:14,n:"contact flow"},mb={id:17,n:"contact flow deep link"},nb={id:20,n:"article survey"},ob={id:21,n:"contact form"},pb={id:22,n:"recaptcha"},qb={id:23,n:"portal"},rb={id:25,n:"troubleshooter"},sb={id:39,n:"screenshot"},tb={id:40,n:"glossary"},ub={id:41,n:"page"},vb={id:42,n:"appbar"},wb={id:43,n:"dynamic_recommendation"},xb={id:44,n:"video"},yb={id:48,n:"chat"},zb={id:49,n:"feedback"},Ab={id:50,n:"forum thread"},Bb={id:51,n:"forum message"},Cb={id:52,n:"contact form c2c"},Db={id:55,n:"forum overflow"},Eb={id:56,n:"forum promoted messages"},Fb={yh:eb,Ql:fb,Sm:gb,vm:{id:3,n:"sibling nav"},Jm:{id:4,n:"top nav"},hm:{id:5,n:"promotion"},Wl:{id:7,n:"notification"},$k:hb,Yk:{id:9,n:"breadcrumbs"},om:ib,rm:jb,sm:{id:12,n:"search results nav"},dm:kb,kl:lb,ql:{id:15,n:"contact flow issues"},rl:{id:16,n:"contact flow login"},ll:mb,Il:{id:18,n:"footer"},wl:{id:19,n:"context selector"},Vk:nb,ul:ob,jm:pb,bm:qb,Im:{id:24,n:"topic"},Lm:rb,Am:{id:26,n:"suggestions"},Ul:{id:27,n:"known issues"},el:{id:28,n:"checklist"},El:{id:29,n:"faq"},Gl:{id:30,n:"faq toc"},Fl:{id:31,n:"faq questions"},Tk:{id:32,n:"appbar"},il:{id:33,n:"community button"},am:{id:34,n:"policy"},Rk:{id:35,n:"answer"},em:{id:36,n:"product button"},mm:{id:37,n:"related items"},Km:{id:38,n:"translate"},nm:sb,Nl:tb,Yl:ub,Uk:vb,Al:wb,Nm:xb,fm:{id:45,n:"product selector"},Ol:{id:46,n:"guide"},tl:{id:47,n:"contact flow recommendation"},bl:yb,Hl:zb,Ml:Ab,Jl:Bb,vl:Cb,Kl:Db,Ll:Eb,Xl:{id:57,n:"one bar"},nl:{id:58,n:"contact flow deep link inline"},Fm:{id:59,n:"support forum thread list"},Gm:{id:60,n:"support forum thread list filter"},Bm:{id:61,n:"support forum ask flow"},Cm:{id:62,n:"support forum display name editor"},Em:{id:63,n:"support forum thread"},Hm:{id:64,n:"support forum thread message"},Dm:{id:65,n:"support forum post widget"}},Gb={id:0,n:"unknown"},Hb={id:1,n:"view"},Ib={id:2,n:"expand"},Jb={id:3,n:"collapse"},Kb={id:4,n:"show"},Lb={id:5,n:"hide"},Mb={id:6,n:"next"},Nb={id:7,n:"previous"},Ob={id:8,n:"select"},Pb={id:9,n:"dismiss"},Qb={id:10,n:"accept"},Rb={id:11,n:"rejected"},Sb={id:12,n:"suggested"},Tb={id:14,n:"answered"},Ub={id:17,n:"invalidated"},Vb={id:18,n:"start"},Wb={id:19,n:"end"},Xb={id:20,n:"initialized"},Yb={id:21,n:"error"},Zb={id:22,n:"submit"},$b={id:23,n:"auto complete"},ac={id:24,n:"edit"},bc={id:25,n:"play"},cc={id:26,n:"pause"},dc=
{id:27,n:"buffer"},ec={id:28,n:"cue"},fc={id:29,n:"deselect"},gc={yh:Gb,Om:Hb,Dl:Ib,fl:Jb,um:Kb,Pl:Lb,Vl:Mb,cm:Nb,tm:Ob,zl:Pb,Pk:Qb,km:Rb,zm:Sb,al:{id:13,n:"categorized"},Sk:Tb,jl:{id:15,n:"completed"},Mm:{id:16,n:"validated"},Tl:Ub,wm:Vb,Cl:Wb,Rl:Xb,ERROR:Yb,ym:Zb,Wk:$b,Bl:ac,$l:bc,Zl:cc,Zk:dc,xl:ec,yl:fc};function hc(a){this.w=[];this.o=[];a=ic.exec(a);this.H=a[1];a[2]&&(this.w=jc(a[2]));a[3]&&(this.o=jc(a[3]))}
var ic=/^([^?#]*)(?:\?([^#]*))?(?:#(.*))?$/;function jc(a){var b=[];a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");b.push({key:decodeURIComponent(d[0]),value:d[1]?decodeURIComponent(d[1]):""})}return b}
function G(a,b,c){return kc(a,a.w,b,c)}
function kc(a,b,c,d){for(var e=0;e<b.length;e++){var f=b[e];if(f.key==c){f.value=d;for(e=e+1||0;e<b.length;)b[e].key==c?b.splice(e,1):e++;return a}}b.push({key:c,value:d});return a}
hc.prototype.toString=function(){var a=this.H;0<this.w.length&&(a+="?"+lc(this.w));0<this.o.length&&(a+="#"+lc(this.o));return a};function lc(a){for(var b="",c=0;c<a.length;c++){b&&(b+="&");var d=a[c];b+=encodeURIComponent(d.key);d.value&&(b+="="+encodeURIComponent(d.value))}return b}
;var mc=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(wa(a))return wa(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},nc=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=wa(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},oc=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=wa(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var m=g[l];b.call(c,m,l,a)&&(e[f++]=m)}return e},pc=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=wa(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},qc=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=wa(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};var rc=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function sc(){return-1!=tc.toLowerCase().indexOf("webkit")}
function uc(a,b){var c=0;a=rc(String(a)).split(".");b=rc(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=vc(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||vc(0==f[2].length,0==g[2].length)||vc(f[2],g[2]);f=f[3];g=g[3]}while(0==c)}return c}
function vc(a,b){return a<b?-1:a>b?1:0}
;var tc;a:{var wc=r.navigator;if(wc){var xc=wc.userAgent;if(xc){tc=xc;break a}}tc=""}function H(a){return-1!=tc.indexOf(a)}
function yc(a){for(var b=/(\w[\w ]+)\/([^\s]+)\s*(?:\((.*?)\))?/g,c=[],d;d=b.exec(a);)c.push([d[1],d[2],d[3]||void 0]);return c}
;function zc(a,b){return null!==a&&b in a}
var Ac="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Bc(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ac.length;f++)c=Ac[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
;function Cc(){return H("Trident")||H("MSIE")}
function Dc(){return(H("Chrome")||H("CriOS"))&&!H("Edge")}
function Ec(){function a(a){a:{var b=d;for(var e=a.length,l=wa(a)?a.split(""):a,m=0;m<e;m++)if(m in l&&b.call(void 0,l[m],m,a)){b=m;break a}b=-1}return c[0>b?null:wa(a)?a.charAt(b):a[b]]||""}
var b=tc;if(Cc())return Fc(b);b=yc(b);var c={};nc(b,function(a){c[a[0]]=a[1]});var d=Ga(zc,c);return H("Opera")?a(["Version","Opera"]):H("Edge")?a(["Edge"]):Dc()?a(["Chrome","CriOS"]):(b=b[2])&&b[1]||""}
function Fc(a){var b=/rv: *([\d\.]*)/.exec(a);if(b&&b[1])return b[1];b="";var c=/MSIE +([\d\.]+)/.exec(a);if(c&&c[1])if(a=/Trident\/(\d.\d)/.exec(a),"7.0"==c[1])if(a&&a[1])switch(a[1]){case "4.0":b="8.0";break;case "5.0":b="9.0";break;case "6.0":b="10.0";break;case "7.0":b="11.0"}else b="7.0";else b=c[1];return b}
;function Gc(){return H("Gecko")&&!(sc()&&!H("Edge"))&&!(H("Trident")||H("MSIE"))&&!H("Edge")}
;function Hc(a){Hc[" "](a);return a}
Hc[" "]=za;var Ic=H("Opera"),Jc=Cc(),Kc=H("Edge"),Lc=Gc(),Mc=sc()&&!H("Edge"),Nc=H("Macintosh");function Oc(){var a=r.document;return a?a.documentMode:void 0}
var Pc;a:{var Qc="",Rc=function(){var a=tc;if(Lc)return/rv:([^\);]+)(\)|;)/.exec(a);if(Kc)return/Edge\/([\d\.]+)/.exec(a);if(Jc)return/\b(?:MSIE|rv)[:]([^\);]+)(\)|;)/.exec(a);if(Mc)return/WebKit\/(\S+)/.exec(a);if(Ic)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Rc&&(Qc=Rc?Rc[1]:"");if(Jc){var Sc=Oc();if(null!=Sc&&Sc>parseFloat(Qc)){Pc=String(Sc);break a}}Pc=Qc}var Tc=Pc,Uc={},Vc;var Wc=r.document;Vc=Wc&&Jc?Oc()||("CSS1Compat"==Wc.compatMode?parseInt(Tc,10):5):void 0;function Xc(){this.o="";this.w=Yc}
Xc.prototype.yb=!0;Xc.prototype.kb=k("o");Xc.prototype.toString=function(){return"Const{"+this.o+"}"};function Zc(a){return a instanceof Xc&&a.constructor===Xc&&a.w===Yc?a.o:"type_error:Const"}
var Yc={};function $c(a){var b=new Xc;b.o=a;return b}
$c("");function ad(){this.o="";this.w=bd}
ad.prototype.yb=!0;ad.prototype.kb=k("o");ad.prototype.ie=!0;ad.prototype.Hb=da(2);function ed(a){if(a instanceof ad&&a.constructor===ad&&a.w===bd)return a.o;Aa(a);return"type_error:TrustedResourceUrl"}
var bd={};function fd(a){var b=new ad;b.o=a;return b}
;function gd(){this.o="";this.w=hd}
gd.prototype.yb=!0;gd.prototype.kb=k("o");gd.prototype.ie=!0;gd.prototype.Hb=da(1);function id(a){if(a instanceof gd&&a.constructor===gd&&a.w===hd)return a.o;Aa(a);return"type_error:SafeUrl"}
var jd=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;function kd(a){if(a instanceof gd)return a;a=a.yb?a.kb():String(a);jd.test(a)||(a="about:invalid#zClosurez");return ld(a)}
var hd={};function ld(a){var b=new gd;b.o=a;return b}
ld("about:blank");function md(){this.o="";this.w=nd}
md.prototype.yb=!0;var nd={};md.prototype.kb=k("o");function od(a){var b=new md;b.o=a;return b}
var pd=od("");function qd(){this.o="";this.H=rd;this.w=null}
qd.prototype.ie=!0;qd.prototype.Hb=da(0);qd.prototype.yb=!0;qd.prototype.kb=k("o");var rd={};function sd(a,b){var c=new qd;c.o=a;c.w=b;return c}
sd("<!DOCTYPE html>",0);sd("",0);sd("<br>",0);function td(){return document.createElement("SCRIPT")}
;function ud(a){vd();return fd(a)}
var vd=za;function wd(){}
;function xd(a,b){this.type=a;this.o=this.target=b;this.w=!1;this.xg=!0}
xd.prototype.stopPropagation=function(){this.w=!0};xd.prototype.preventDefault=function(){this.xg=!1};var yd;(yd=!Jc)||(yd=9<=Number(Vc));var zd=yd,Ad;if(Ad=Jc)Ad=!(Object.prototype.hasOwnProperty.call(Uc,"9")?Uc["9"]:Uc["9"]=0<=uc(Tc,"9"));var Bd=Ad,Cd=function(){if(!r.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});r.addEventListener("test",za,b);r.removeEventListener("test",za,b);return a}();function Dd(a,b){xd.call(this,a?a.type:"");this.relatedTarget=this.o=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.H=null;a&&this.init(a,b)}
w(Dd,xd);var Ed={2:"touch",3:"pen",4:"mouse"};Dd.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.o=b;if(b=a.relatedTarget){if(Lc){a:{try{Hc(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;null===d?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=
void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=wa(a.pointerType)?a.pointerType:Ed[a.pointerType]||"";this.H=a;a.defaultPrevented&&this.preventDefault()};Dd.prototype.stopPropagation=function(){Dd.Mc.stopPropagation.call(this);this.H.stopPropagation?this.H.stopPropagation():this.H.cancelBubble=!0};Dd.prototype.preventDefault=function(){Dd.Mc.preventDefault.call(this);var a=this.H;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Bd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Fd="closure_listenable_"+(1E6*Math.random()|0),Gd=0;function Hd(a,b,c,d,e){this.listener=a;this.o=null;this.src=b;this.type=c;this.capture=!!d;this.sd=e;this.key=++Gd;this.vc=this.Xc=!1}
function Id(a){a.vc=!0;a.listener=null;a.o=null;a.src=null;a.sd=null}
;function Jd(a){this.src=a;this.o={};this.w=0}
Jd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.o[f];a||(a=this.o[f]=[],this.w++);var g=Kd(a,b,d,e);-1<g?(b=a[g],c||(b.Xc=!1)):(b=new Hd(b,this.src,f,!!d,e),b.Xc=c,a.push(b));return b};Jd.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.o))return!1;var e=this.o[a];b=Kd(e,b,c,d);return-1<b?(Id(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.o[a],this.w--),!0):!1};function Ld(a,b){var c=b.type;if(c in a.o){var d=a.o[c],e=mc(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(Id(b),0==a.o[c].length&&(delete a.o[c],a.w--))}}
function Kd(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.vc&&f.listener==b&&f.capture==!!c&&f.sd==d)return e}return-1}
;var Md="closure_lm_"+(1E6*Math.random()|0),Nd={},Od=0;function Pd(a,b,c,d,e){if(d&&d.once)Qd(a,b,c,d,e);else if(Ba(b))for(var f=0;f<b.length;f++)Pd(a,b[f],c,d,e);else c=Rd(c),a&&a[Fd]?a.Gf(b,c,Da(d)?!!d.capture:!!d,e):Sd(a,b,c,!1,d,e)}
function Sd(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=Da(e)?!!e.capture:!!e,l=Td(a);l||(a[Md]=l=new Jd(a));c=l.add(b,c,d,g,f);if(!c.o){d=Ud();c.o=d;d.src=a;d.listener=c;if(a.addEventListener)Cd||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Vd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Od++}}
function Ud(){var a=Wd,b=zd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}
function Qd(a,b,c,d,e){if(Ba(b))for(var f=0;f<b.length;f++)Qd(a,b[f],c,d,e);else c=Rd(c),a&&a[Fd]?a.Rf(b,c,Da(d)?!!d.capture:!!d,e):Sd(a,b,c,!0,d,e)}
function Xd(a,b,c,d,e){if(Ba(b))for(var f=0;f<b.length;f++)Xd(a,b[f],c,d,e);else(d=Da(d)?!!d.capture:!!d,c=Rd(c),a&&a[Fd])?a.Hf(b,c,d,e):a&&(a=Td(a))&&(b=a.o[b.toString()],a=-1,b&&(a=Kd(b,c,d,e)),(c=-1<a?b[a]:null)&&Yd(c))}
function Yd(a){if(!xa(a)&&a&&!a.vc){var b=a.src;if(b&&b[Fd])b.Oe(a);else{var c=a.type,d=a.o;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Vd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Od--;(c=Td(b))?(Ld(c,a),0==c.w&&(c.src=null,b[Md]=null)):Id(a)}}}
function Vd(a){return a in Nd?Nd[a]:Nd[a]="on"+a}
function Zd(a,b,c,d){var e=!0;if(a=Td(a))if(b=a.o[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.vc&&(f=$d(f,d),e=e&&!1!==f)}return e}
function $d(a,b){var c=a.listener,d=a.sd||a.src;a.Xc&&Yd(a);return c.call(d,b)}
function Wd(a,b){if(a.vc)return!0;if(!zd){var c=b||ya("window.event");b=new Dd(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.o;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.w&&0<=e;e--){b.o=c[e];var f=Zd(c[e],a,!0,b);d=d&&f}for(e=0;!b.w&&e<c.length;e++)b.o=c[e],f=Zd(c[e],a,!1,b),d=d&&f}return d}return $d(a,new Dd(b,this))}
function Td(a){a=a[Md];return a instanceof Jd?a:null}
var ae="__closure_events_fn_"+(1E9*Math.random()>>>0);function Rd(a){if(Ca(a))return a;a[ae]||(a[ae]=function(b){return a.handleEvent(b)});return a[ae]}
;function be(){this.o=new Jd(this);this.w=this}
w(be,wd);be.prototype[Fd]=!0;p=be.prototype;p.ae=ba(null);p.addEventListener=function(a,b,c,d){Pd(this,a,b,c,d)};p.removeEventListener=function(a,b,c,d){Xd(this,a,b,c,d)};p.qd=function(a){var b=this.ae();if(b){var c=[];for(var d=1;b;b=b.ae())c.push(b),++d}b=this.w;d=a.type||a;if(wa(a))a=new xd(a,b);else if(a instanceof xd)a.target=a.target||b;else{var e=a;a=new xd(d,b);Bc(a,e)}e=!0;if(c)for(var f=c.length-1;!a.w&&0<=f;f--){var g=a.o=c[f];e=g.Ac(d,!0,a)&&e}a.w||(g=a.o=b,e=g.Ac(d,!0,a)&&e,a.w||(e=g.Ac(d,!1,a)&&e));if(c)for(f=0;!a.w&&f<c.length;f++)g=a.o=c[f],e=g.Ac(d,!1,a)&&e};p.Gf=function(a,b,c,d){this.o.add(String(a),b,!1,c,d)};p.Rf=function(a,b,c,d){this.o.add(String(a),b,!0,c,d)};p.Hf=function(a,b,c,d){this.o.remove(String(a),b,c,d)};p.Oe=function(a){Ld(this.o,a)};p.Ac=function(a,b,c){a=this.o.o[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.vc&&f.capture==b){var g=f.listener,l=f.sd||f.src;f.Xc&&this.Oe(f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.xg};function ce(a){this.o=a;this.w=[]}
var de=!1;function I(a){if(!(a in ee)){var b=F().querySelector('[data-page-data-key="'+a+'"]');if(!b)return"";ee[a]=b.textContent}return ee[a]}
var ee={},fe={};function ge(a){switch(a.tagName){case "BUTTON":case "INPUT":case "OPTION":case "SELECT":return!0}return!1}
ce.prototype.init=function(){he(this);!this.o.visit_id&&window.sc_visit_id&&(this.o.visit_id=window.sc_visit_id);if(!de){var a=document.getElementsByTagName("body")[0],b=this.R.bind(this);a.addEventListener("click",b);de=!0;document.addEventListener("pjaxunload",function(){a.removeEventListener("click",b);de=!1})}ie();je(this);this.o.fragment&&(window.location.hash=this.o.fragment)};ce.prototype.H=function(a){for(var b=0;b<a.length;b++)this.w.push(a[b])};ce.prototype.R=function(a){for(var b=1!==a.target.nodeType?a.target.parentNode:a.target,c=!1,d=!1,e="",f=!1;b&&b.getAttribute;){var g=b.getAttribute("href");if("A"===b.nodeName&&g){f="_blank"==b.target||a.ctrlKey||a.shiftKey||a.metaKey||1==a.button;$a(b)?c=!0:"#"!=b.getAttribute("href")[0]&&(d=!0,e=bb(b));break}else if(ge(b))break;else b=b.parentNode}a={event:a,element:b,blank:f,external:c,hc_internal:d,href:g,target_hc:e};window.sc_visitManagerProcessClick(a);for(b=0;b<this.w.length;b++)this.w[b](a)};function ie(){for(var a=(window.sc_scope||document).querySelectorAll("select"),b=0;b<a.length;b++){var c=a[b];c.addEventListener("mousedown",function(){cb(!0)});c.addEventListener("change",function(){cb(!1)})}}
function he(a){var b=[];if(window.localStorage)try{var c=window.localStorage;c.setItem("__storage_test__","__storage_test__");c.removeItem("__storage_test__")}catch(d){b.push(2)}else b.push(1);navigator.cookieEnabled||b.push(3);0<b.length&&(a.o.request_attributes=b)}
function je(a){a.H([function(a){a.href&&"#"==a.href[0]&&ke(a.href.substring(1))&&a.event.preventDefault()}.bind(a)]);window.addEventListener("hashchange",function(a){ke(window.location.hash.substring(1))&&a.preventDefault()}.bind(a));window.addEventListener("load",function(){ke(window.location.hash.substring(1))}.bind(a))}
function ke(a){a=document.getElementById(a)||document.getElementsByName(a)[0];if(!a)return!1;var b=db();if(!b)return!1;window.scroll(0,window.pageYOffset+a.getBoundingClientRect().top-b);return!0}
window.sc_initPage=function(a){a=new ce(a);a.init();if(1==window.sc_refresh){var b;window.sc_pageModel&&(b=window.sc_pageModel.iro);window.sc_pageModel=a.o;b&&(window.sc_pageModel.iro=b);window.sc_registerPageClickHandlers=a.H.bind(a)}};v("hcfe.Page",ce);v("hcfe.Page.setString",function(a,b){fe[a]=b});v("hcfe.Page.getString",function(a){return fe[a]});function le(){var a=document.body||document.documentElement;a:{var b=9==a.nodeType?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.direction||b.getPropertyValue("direction")||"";break a}b=""}return b||(a.currentStyle?a.currentStyle.direction:null)||a.style&&a.style.direction}
;var me=/^[6-9]$/,ne=/<\/?(?:b|em)>/gi;function oe(a){this.o=a}
var pe=new oe({});oe.prototype.Wa=function(a){return this.o[a]||""};function qe(a,b,c,d,e,f){this.V=a;this.o=b;this.H=c;this.R=d;this.S=e;this.W=f||pe;this.w=!1;switch(this.R){case 0:case 32:case 38:case 400:case 407:case 35:case 33:case 41:case 34:case 44:case 45:case 40:case 46:case 56:case 30:case 411:case 410:case 71:case 42:this.w=!0}}
qe.prototype.Nb=k("V");qe.prototype.T=k("H");qe.prototype.Ga=k("R");qe.prototype.getParameters=k("W");var re=/^\s/,se=/\s+/,te=/\s+/g,ue=/^\s+|\s+$/g,ve=/^\s+$/,we=/<[^>]*>/g,xe=/&nbsp;/g,ye=/&#x3000;/g,ze=[/&/g,/&amp;/g,/</g,/&lt;/g,/>/g,/&gt;/g,/"/g,/&quot;/g,/'/g,/&#39;/g,/{/g,/&#123;/g],Ae=document.getElementsByTagName("head")[0],Be=0,Ce=1;function De(a){var b={};if(a)for(var c=0;c<a.length;++c)b[a[c]]=!0;return b}
function Ee(a,b){function c(){return b}
void 0===b&&(b=a);return{od:c,Cf:function(){return a},yi:c,qn:function(){return a<b},an:function(c){return c&&a==c.Cf()&&b==c.yi()}}}
function Fe(a,b,c,d){if(null==b||""===b){if(!d)return;b=""}c.push(a+"="+encodeURIComponent(String(b)))}
function Ge(a){return!!a&&!ve.test(a)}
function He(a){for(var b=ze.length,c=0;c<b;c+=2)a=a.replace(ze[c],ze[c+1].source);return a}
function Ie(a){for(var b=ze.length,c=0;c<b;c+=2)a=a.replace(ze[c+1],ze[c].source);a=a.replace(xe," ");return a.replace(ye,"\u3000")}
function Je(a,b){return a&&(-1<a.indexOf(" ")||se.test(a))?(a=a.replace(te," "),a.replace(b?ue:re,"")):a}
function Ke(a,b,c){c&&(a=a.toLowerCase(),b=b.toLowerCase());return b.length<=a.length&&a.substring(0,b.length)==b}
function Le(){}
function Me(a){var b=Ne;if(b.indexOf)return b.indexOf(a);for(var c=0,d=b.length;c<d;++c)if(b[c]===a)return c;return-1}
function Oe(a,b){return b.o()-a.o()}
function Pe(a){var b={},c;for(c in a)b[c]=a[c];return b}
;function Qe(a,b){this.o=a;this.ma=b;this.w=(Be++).toString(36);this.ka=this.o.toLowerCase();this.W=Je(this.ka);this.ha={};this.H={};this.S=this.R=!1;this.V=1}
Qe.prototype.getId=k("w");function Re(a){a=parseInt(a.w,36);return isNaN(a)?-1:a}
Qe.prototype.getParameters=k("ha");function Se(a,b,c,d){a.R||(a.ha[b]=c,d&&(a.H[b]=c))}
;function Te(a,b,c,d,e){this.o=a;this.w=b;this.H=c;this.S=d;this.R=e;this.T=!0;this.w?this.w.length&&33==this.w[0].Ga()&&(this.R=this.T=!1):this.w=[];this.H||(this.H=pe)}
Te.prototype.getParameters=k("H");Te.prototype.Ga=k("T");function Ue(){}
p=Ue.prototype;p.search=h();p.redirect=h();p.nf=h();p.qf=h();p.Uf=h();p.rf=h();function Ve(){this.w={};this.o={}}
Ve.prototype.set=function(a,b){this.w[a]=b};Ve.prototype.has=function(a){return!!this.w[a]};function We(a,b,c){b in a.o||(a.o[b]=[]);a.o[b].push(c)}
;function Xe(a,b,c,d,e,f){this.T=a;this.ha=b;this.ka=c;this.R=d;this.S=e;this.V=f;this.W={};this.o={};this.w=[];this.H=!1;a=this.ha;d=a.w;for(var g in d)if(b=g,c=d[b])this.W[b]=c,this.w.push(c);a=a.o;for(g in a){b=g;d=c=a[b];e=this.o[b]||[];for(f=0;f<d.length;++f)if(c=d[f])e.push(c),this.w.push(c);this.o[b]=e}this.w.sort(Ye);for(g=0;a=this.w[g++];)a.Pb(this.ka,this.R);this.T.Uf(this.R);this.R.Bh();for(g=0;a=this.w[g++];)a.Qa(this);for(g=0;a=this.w[g++];)a.setup(this.V);for(g=0;a=this.w[g++];)a.ad(this.V);for(g=0;a=this.w[g++];)a.activate(this.V);this.H=!0}
var Ne=[127,149,134,494,123,121,126,553,118,115,128,160,173,119,116,152,153,129,120,374,124,158,155,131,130,147,570,141,142,137,143,138,144,139,140,135,136];Xe.prototype.activate=function(a){this.deactivate();for(var b=0,c;c=this.w[b++];)c.activate(a);this.H=!0};Xe.prototype.deactivate=function(){if(this.H){for(var a=0,b;b=this.w[a++];)b.deactivate();this.H=!1}};Xe.prototype.get=function(a){return this.W[a]};function Ye(a,b){a=Me(a.Ga());b=Me(b.Ga());return 0>a?1:0>b?-1:a-b}
;function J(a){this.w=a}
p=J.prototype;p.Pb=h();p.Qa=h();p.setup=h();p.ad=h();p.activate=h();p.Ga=k("w");p.deactivate=h();function Ze(a){this.S=a}
Ze.prototype.Ga=k("S");Ze.prototype.R=ba(!0);function $e(a){this.w=152;this.S=a}
w($e,J);$e.prototype.o=Le;$e.prototype.R=function(a){return a.o};var af=Cc(),bf=af&&0<=uc(Ec(),10),cf=Gc();cf&&Ec();var df=H("Opera"),ef=sc()&&!H("Edge"),ff=H("Safari")&&!(Dc()||H("Coast")||H("Opera")||H("Edge")||H("Silk")||H("Android")),gf=Dc(),hf=H("Android"),jf=H("Macintosh"),kf=!(H("iPad")||H("Android")&&!H("Mobile")||H("Silk"))&&(H("iPod")||H("iPhone")||H("Android")||H("IEMobile"));var lf={rtl:"right",ltr:"left"};function mf(a,b){try{if(a.setSelectionRange)a.setSelectionRange(b,b);else if(a.createTextRange){var c=a.createTextRange();c.collapse(!0);c.moveStart("character",b);c.select()}}catch(d){}}
function nf(a){for(var b=0,c=0;a;){b+=a.offsetTop;c+=a.offsetLeft;try{a=a.offsetParent}catch(d){a=null}}return{Cd:b,Ib:c}}
function of(a){try{return pf(a).activeElement==a}catch(b){}return!1}
function qf(a,b){a=document.createElement(a);b&&(a.className=b);return a}
function rf(a){return qf("div",a)}
function sf(a,b){a.dir!=b&&(a.dir=b,a.style.textAlign=lf[b])}
function tf(a){var b=a||window;a=b.document;var c=b.innerWidth;b=b.innerHeight;if(!c){var d=a.documentElement;d&&(c=d.clientWidth,b=d.clientHeight);c||(c=a.body.clientWidth,b=a.body.clientHeight)}return{xc:c,Lf:b}}
function pf(a){return a?a.ownerDocument||a.document:window.document}
function uf(a){return a?(a=pf(a),a.defaultView||a.parentWindow):window}
;function vf(){this.S=79;this.o=this.H=this.w=null;this.w=rf();var a=rf("ghp-autocomplete-icon");this.H=rf();a.appendChild(this.H);this.w.appendChild(a);this.o=rf();this.w.appendChild(this.o)}
w(vf,Ze);vf.prototype.R=ba(!0);vf.prototype.render=function(a,b,c){if(c){var d=c.Wa("t")||"";b=c.o.p||null;a=c.Wa("l")||a;if("ADWORDS_NAVI"==d)this.H.className="action-adwords-navi-icon",this.o.innerHTML=a,this.o.className="ghp-autocomplete-label";else if("GUIDED_HELP"==d)this.H.className="action-guided-help-icon",this.o.innerHTML=a,this.o.className="ghp-autocomplete-label";else if("HELP_ARTICLE"==d)this.H.className="help-article-icon",this.o.innerHTML=a,this.o.className="ghp-autocomplete-label";else if("HELP_ACTION"==d){if(this.H.className=
"action-command-icon",this.o.innerHTML=a,this.o.className="ghp-autocomplete-label action-command-title",b){a={};b.result&&(a=JSON.parse(b.result));if("JS_CALLBACK"===a.type)b={type:a.type,jsCallback:{closePanel:"true"===(a.jsCallback||{}).closePanel}};else if("URL_NAVIGATION_ACTION"===a.type)b=a.urlNavigationDefinition,b={type:a.type,urlNavigationDefinition:{createNewTab:"true"===b.createNewTab,url:b.url}};else throw Error("Invalid help action result type: "+a.type);b=b||{};"URL_NAVIGATION_ACTION"==
b.type&&ya("urlNavigationDefinition.createNewTab",b)&&(this.o.className+=" ghp-autocomplete-externalLink")}}else"SUPPORT_THREAD"==d&&(this.H.className="support-forum-icon",this.o.textContent=a,this.o.className="ghp-autocomplete-label")}else this.H.className="search-query-icon",this.o.innerHTML=a,this.o.className="ghp-autocomplete-label"};function wf(){$e.call(this,79)}
w(wf,$e);wf.prototype.H=function(){return new vf};wf.prototype.render=function(a,b){b.render(a.Nb(),a.o,a.getParameters())};wf.prototype.o=function(a,b,c){c.search(b.o,1)};wf.prototype.R=function(a,b){return"GUIDED_HELP"==a.getParameters().Wa("t")?b:a.o};function xf(){$e.call(this,0)}
w(xf,$e);xf.prototype.H=function(){return new vf};xf.prototype.render=function(a,b){b.render(a.Nb(),a.o)};xf.prototype.o=function(a,b,c){c.search(b.o,1)};function yf(a){this.w=156;this.o=a}
w(yf,J);function zf(a){var b=oc(a,function(a){return"HELP_ACTION"==a.getParameters().Wa("t")});a=oc(a,function(a){return"HELP_ACTION"!=a.getParameters().Wa("t")});return b.concat(a)}
function Af(a,b,c){this.w=122;this.R=a;this.H=b||[];this.o=c||null}
w(Af,J);function Bf(a,b){var c=oc(b.w,function(a){if(!a)return!1;a=a.getParameters().Wa("t");return!a||0<=this.H.indexOf(a)},a);a.o&&(c=oc(c,function(a){var b=a.getParameters().o.p||{};return this.o.filter(a.getParameters().Wa("t"),b)},a));c=zf(c);c=pc(c,function(a,b){return new qe(a.Nb(),a.o,b,a.Ga(),a.S||[],a.getParameters())},a);c=c.slice(0,a.R);return new Te(b.o,c,b.getParameters(),b.S,b.R)}
;function Cf(){this.w=157}
w(Cf,J);function Df(){this.w=149;this.R=Ae;this.o={}}
w(Df,J);p=Df.prototype;p.Qa=function(a){this.ra=a.get(127);this.W=a.S.getId()};p.setup=function(){"google"in window||(window.google={});"sbox"in window.google||(window.google.sbox={})};p.activate=function(a){this.H=a;0==a.Nd&&(a=this.ra.R,this.V=a.protocol,this.T=a.host,this.ma=a.ve,this.ha=a.tk,this.ka="https:"==document.location.protocol,Ef(this,t(this.jk,this)),(new Image).src=this.V+this.T+"/generate_204")};p.deactivate=function(){Ef(this,null);Ff(this)};function Ff(a){for(var b in a.o)a.R.removeChild(a.o[b]);a.o={};a.S=null}
p.jk=function(a){this.S&&this.S(a)};function Ef(a,b){b||(b=Le);var c=window.google;a.H.$g?c.ac.h=b:c.sbox["p"+a.W]=b}
;function Gf(){this.w=115;this.R={}}
w(Gf,J);var Hf={Nf:"left",mj:!0,$b:null,marginWidth:0};p=Gf.prototype;p.Qa=function(a){this.S=a.get(116);a=a.o[154]||[];for(var b=0,c;c=a[b++];)this.R[If]=c};p.activate=function(){this.H=!1};p.deactivate=function(){Jf(this)};p.Bb=k("H");p.show=function(){this.H||(this.S.show(Kf(this)),this.H=!0)};function Jf(a){if(a.H){var b=a.S;b.ka=0;Lf(b.V.R,!1);Mf(b.va,!1);Mf(b.R,!1);Nf(b,b.Ca);Of(b.ua,9);a.H=!1}}
function Kf(a){var b=Pe(Hf);if(a.o){a=a.o.H;b.$b=a.ha;b.marginWidth=a.va;var c=a.ma.xk;c||(c="rtl"==a.ha?"right":"left");b.Nf=c}return b}
;function Pf(){this.w=118}
w(Pf,J);p=Pf.prototype;p.Qa=function(a){this.R=a.get(119);this.ka=a.get(130);this.Ca=a.get(145);this.V=a.get(117);this.wa=a.get(123);this.ma=a.get(374);this.va=a.get(121);this.Da=a.get(553);this.H=a.get(128);this.ya=a.get(139);this.Fa=a.get(173);this.Ia=a.o[160]||[]};p.setup=function(a){this.T=a;this.o=this.S=this.R.o.value||""};p.activate=function(a){this.T=a;this.ha=this.ta=!1;Qf(this)};function Rf(a){var b={};Of(a.V,11,b);!b.cancel&&a.T.$i&&Sf(a.V,function(){a.H.bc()})}
function Tf(a){if(0==a.T.Tg||2==a.T.Tg)return!1;a:{if(Uf(a.H)){if(null!=a.H.R)var b=Vf(a.H);else b=a.H,b=Uf(b)?b.H[0]:null;if(b.w)break a}b=null}var c;if(c=b)b=b.o,((c=a.S)||b?c&&b&&c.toLowerCase()==b.toLowerCase():1)?c=!1:(a.S=a.o,Ke(b,a.o,!0)&&(b=a.o+b.substr(a.o.length)),Wf(a,b,Ee(b.length),"",!0),Xf(a,b,!0),c=!0);return c?(a.ma.add(8),!0):!1}
function Wf(a,b,c,d,e){a.T.Nh&&!a.H.Bb()&&"mousedown"==d&&Yf(a.H,c);var f=!1,g=!1;if(b!=a.o||"onremovechip"==d)Ke(d,"key")?a.ma.add(1):"paste"==d&&a.ma.add(2),f=!0,Zf(a,b),Of(a.V,1,{Nc:d,$b:a.W}),g=Ha(),a.ra||(a.ra=g),a.ua=g,Ge(b)&&(e=!0),g=!0;b=$f(a.Da,b,c);switch(b.V){case 2:e=!0;break;case 3:e=!1}e?(f&&(f=a.H,f.T&&!f.V&&(f.V=window.setTimeout(t(f.clear,f),f.ma.aj))),a.ta&&Se(b,"gs_is",1),ag(a.wa,b)):g&&(a.H.clear(),f=a.wa,f.V=f.S);Of(a.V,2,{Nc:d})}
function bg(a){a=a.R;a.T&&(a.o.blur(),a.T=!1)}
function cg(a){a.o!=a.S&&Zf(a,a.S);Of(a.V,5,{input:a.S,wk:a.H.H,$b:a.W});dg(a.R)}
function eg(a){if(a.Fa){if(a.T.Ri)return!0;for(var b=0,c;c=a.Ia[b++];)if(c.o())return!0}return!1}
p.search=function(a){this.va.search(this.o,a)};p.clear=function(){this.o&&(Zf(this,""),this.R.clear(),Of(this.V,1),Of(this.V,16),this.H.clear())};function fg(a,b){var c=a.R.V.od();a.W==b?Uf(a.H)&&c==a.o.length&&(null!=a.H.R?a.T.Vd&&a.va.search(Vf(a.H).o,6):a.T.yj&&Tf(a)):a.ka&&0==c&&a.ka.o()}
function Xf(a,b,c){a.o=b||"";Qf(a);dg(a.R);c||Of(a.V,4,{$b:a.W,input:a.o})}
function Qf(a){var b=gg(a.Ca,a.o);if(b!=a.W){var c=a.R;c.ha&&(c.ha.dir=b);c.o.dir=b;c.W&&(c.W.dir=b);c.ta&&c.ta.w(b);if(c.Ua){c=c.o;var d=0,e=c.style;"INPUT"!=c.nodeName&&(d+=1);e.left=e.right="";e["rtl"==b?"right":"left"]=d+"px"}a.W=b}}
function Zf(a,b){a.o=a.S=b||"";Qf(a)}
;function hg(){this.w=128}
w(hg,J);p=hg.prototype;p.Qa=function(a){this.S=a.get(129);this.ya=a.get(145);this.ua=a.get(115);this.Aa=a.get(123);this.W=a.get(118);this.Da=a.get(147);this.wa=a.o[153]||[];this.Fa=a.get(553);this.ra=a.get(184);this.Ia=a.get(157);this.ta=a.T};p.setup=function(){this.wa.sort(Oe)};p.activate=function(a){this.ma=a;this.R=this.o=null;this.T=this.ka=!1;this.Ca=!0;this.ha="";this.va=0};p.deactivate=function(){this.V&&(window.clearTimeout(this.V),this.V=null);this.H=null;ig(this)};function jg(a,b){if(a.o!=b){var c=a.o;a.o=b;kg(a,c)}}
p.zg=function(){if(Uf(this))if(this.T){var a=this.o;this.o==this.H.length-1?this.R=this.o=null:null==this.o?this.o=0:++this.o;this.R=this.o;lg(this,a,t(this.zg,this))}else this.show()};p.Ag=function(){if(Uf(this))if(this.T){var a=this.o;this.H&&0!=this.o?null==this.o?this.o=this.H.length-1:--this.o:this.R=this.o=null;this.R=this.o;lg(this,a,t(this.Ag,this))}else this.show()};p.Bb=k("T");function Vf(a){return null!=a.R?a.H[a.R]:null}
function Uf(a){return!(!a.H||!a.H.length)}
p.show=function(){if(!this.T){a:{var a=this.ua,b=If;if(b in a.R){if(a.o){if(b==If)break a;Jf(a);a.o.H.T=!1}a.o=a.R[b];b=a.S;a=a.o;a!=b.W&&(b.W=a,a=a.o.S,b.ra?a!=b.ra&&b.T.replaceChild(a,b.ra):b.T.appendChild(a),b.ra=a)}}this.ua.show();this.T=!0;this.ta.nf()}};function ig(a){a.T&&(a.V&&(window.clearTimeout(a.V),a.V=null),Jf(a.ua),a.T=!1,a.ta.qf())}
p.clear=function(){ig(this);this.H=null;this.ka=!1;null!=this.o&&mg(this.S,this.o);this.R=this.o=null;this.S.clear()};p.bc=function(){var a=this.Aa;a.V=a.S;ig(this)};function og(a){null!=a.o&&mg(a.S,a.o);a.R=a.o=null}
function Yf(a,b){if(Uf(a))a.show();else{var c=a.W.S;c&&(b=$f(a.Fa,c,b||a.W.R.V),ag(a.Aa,b))}}
function pg(a){if(Uf(a)&&!a.ka){for(var b=[],c=[],d=0,e;(e=a.wa[d++])&&!e.w(a.W.S,a.H,c););(d=c?c.length:0)&&(d-=qg(c,b,0));for(e=0;e<a.H.length;++e)b.push(a.H[e]);d&&(d-=qg(c,b,1));a.ma.Ui&&b.push(1);d&&qg(c,b,2);a.ma.Kf&&b.push(2);if(a.Ia)for(a=-1,c=0;c<b.length;c++)d=b[c],d=(d=d.getParameters&&d.getParameters())&&d.Wa&&d.Wa("t"),"HELP_ACTION"!=d&&"HELP_ACTION"==a&&(b.splice(c,0,3),c++),a=d;return b}return null}
function qg(a,b,c){for(var d=0,e=0,f;e<a.length;++e)(f=a[e])&&f.position==c&&(b.push(f),++d);return d}
function lg(a,b,c){var d;(d=null==a.o)||(d=(d=a.S.ha[a.o])?d.R():!1);d?(kg(a,b),null==a.o?cg(a.W):(b=a.S,c=a.H[a.o],b=b.ya[c.Ga()].R(c,b.R.S),Xf(a.W,b),a.ta.rf())):(mg(a.S,b),c())}
function kg(a,b){null!=b&&mg(a.S,b);if(null!=a.o&&(b=a.S,a=b.ha[a.o])){if(a.R()){var c=a.w.parentNode,d=b.va;c.classList?c.classList.add(d):rg(c,d)||(c.className+=0<c.className.length?" "+d:d)}b.R.R.o.setAttribute("aria-activedescendant",a.w.id)}}
var If=Ce++;function sg(){this.w=154}
w(sg,J);sg.prototype.Qa=function(a){this.H=a.get(128);this.o=a.get(129)};function tg(){this.w=145;this.o=ug.test("x")}
w(tg,J);var vg=/^[\x00- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*$/,ug=/^[\x00- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*(?:\d[\x00- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*$|[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u2c00-\ufb1c\ufdfe-\ufe6f\ufefd-\uffff])/;tg.prototype.Pb=function(a){this.H=a.$d()};function gg(a,b){var c=a.H;a.o&&(ug.test(b)?c="ltr":vg.test(b)||(c="rtl"));return c}
;function wg(){this.w=117;this.R=[];this.H={nh:1}}
w(wg,J);var xg=window.postMessage&&!(af||ff||df);wg.prototype.deactivate=function(){this.o=null};function yg(a,b,c,d,e,f){var g=zg(a,b);g||(g={},a.R.push({element:b,Mi:g}));var l=g[c];l||(l=g[c]=[],a=Ag(a,c,b.nh?window:uf(b),l),wa(c)?b.addEventListener?b.addEventListener(c,a,!1):b["on"+c]=a:b[c]=a);l.push({lj:!!f,ke:!1,priority:e||0,uc:d});l.sort(Bg);d.Xh=c}
function Cg(a,b,c){if(a=zg(a,b))if(a=a[c.Xh]){b=0;for(var d;d=a[b++];)if(d.uc==c){d.ke=!0;break}}}
function Of(a,b,c){c=c||{};(a=a.H[b])&&a(c,c.Nc)}
function Dg(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)}
function Sf(a,b){if(xg){if(!a.o){a.o=[];var c=t(a.S,a);Dg(window,"message",c)}a.o.push(b);a=window.location.href;window.postMessage("sbox.df",/HTTPS?:\/\//i.test(a)?a:"*")}else window.setTimeout(b,0)}
wg.prototype.S=function(a){this.o&&a&&a.source==window&&"sbox.df"==a.data&&this.o.length&&(this.o.shift()(),this.o&&this.o.length&&window.postMessage("sbox.df",window.location.href))};function Ag(a,b,c,d){return t(function(a,f){if(d.length){if(!a){a={};var e=c.event;e&&(e.keyCode&&(a.keyCode=e.keyCode),a.kj=!0)}a.Nc=f||b;f=a;var l,m;e=0;for(var n;n=d[e++];)n.ke?m=!0:l||(n.lj?Eg(this,n,f):l=n.uc(f));if(m)for(e=0;n=d[e];)n.ke?d.splice(e,1):++e;if(a.vd){delete a.vd;a.kj&&(a=c.event||a);if(l=a||window.event)l.stopPropagation&&l.stopPropagation(),l.cancelBubble=l.cancel=!0;l&&(l.preventDefault&&l.preventDefault(),l.returnValue=!1);return a.returnValue=!1}}},a)}
function zg(a,b){for(var c=0,d;c<a.R.length;++c)if(d=a.R[c],d.element==b)return d.Mi;return null}
function Eg(a,b,c){Sf(a,function(){b.uc(c)})}
function Bg(a,b){return b.priority-a.priority}
;function Fg(){this.w=494;this.o={};this.H=this.S=0;this.R=-1}
w(Fg,J);Fg.prototype.activate=function(){this.reset()};Fg.prototype.reset=function(){this.o={};this.H=this.S=0;this.R=-1};function Gg(){this.w=374}
w(Gg,J);Gg.prototype.activate=function(){this.reset()};Gg.prototype.add=function(a){this.o[a]=!0};Gg.prototype.reset=function(){this.o={}};function Hg(){this.w=120;this.ma=-1}
w(Hg,J);var Ig=/\.+$/,Jg=/\./g,Kg=/./g,Lg=De([23]);p=Hg.prototype;p.Qa=function(a){this.ta=a.get(191);this.o=a.get(123);this.R=a.get(118);this.ha=a.get(374);this.S=a.get(494);this.ka=a.get(126);this.V=a.get(128);this.ra=a.o[311]||[]};p.setup=function(a){this.W=a.uj};p.activate=function(a){this.H=a;this.reset()};p.getParameters=function(a,b){var c=this.R.S;b&&(c=c.replace(Kg,"#"));b=[];b[27]=55;b[0]=Mg(this.H.Ld);b[28]=Mg(this.H.we);b[1]=void 0==a?"":a+"";a=this.ha;var d=[];for(e in a.o)d.push(parseInt(e,10));b[26]=d.join("j");var e="";10<=this.ka.H.W?e="o":null!=this.V.R&&(e=this.V.R+"");b[2]=e;e="";if(a=this.V.H){for(var f=d=0,g;g=a[f++];){var l=g;g=l.Ga()+"";l=l.S||[];l.length&&(g+="i"+l.join("i"));if(g!=m){1<d&&(e+="l"+d);e+=(m?"j":"")+g;d=0;var m=g}++d}1<d&&(e+="l"+d)}b[3]=e;m=this.S.R;b[33]=-1<m?String(m):"";b[4]=Math.max(this.R.ra-this.T,0);b[5]=Math.max(this.R.ua-this.T,0);b[6]=this.ma;b[7]=Ha()-this.T;b[18]=Math.max(this.R.Aa-this.T,0);b[8]=this.o.Ua;e=this.o;e=(m=e.R)?e.H.o():0;b[25]=m?"1"+(this.H.Qh?"a":"")+(this.H.Sh?"c":""):"";b[10]=e;m=this.o;m=m.R?m.H.w():0;b[11]=m;b[12]=this.o.ya;a=this.o;m=a.va;e=a.Ya;a=a.wa;b[9]=m;b[22]=e;b[17]=a;b[13]=this.o.Aa;b[14]=this.o.ra;b[15]=this.o.ua;m=this.o;e=[];for(d=f=0;d<=Ng;++d)a=m.ta[d],0==a?f++:(f=1==f?"0j":1<f?d+"-":"",e.push(f+a),f=0);b[16]=e.join("j");m=0;for(var n in this.S.o)m++;b[30]=m;b[31]=this.S.S;b[32]=this.S.H;b[19]=Mg(this.H.Sg);n=(n=this.ka.o)?n.getParameters().Wa("e")||"":"";b[20]=n;for(n=0;m=this.ra[n++];)e=m.H,Lg[e]&&(b[e]=void 0==b[e]?Mg(m.o()):"");b=b.join(".").replace(Ig,"");if(this.ta&&this.W){n=c+b;b:{m=this.W;e=[];if(m)for(f=d=a=0;f<m.length;++f){g=m.charCodeAt(f);if(32>g||127<g||!Og[g-32]){m=[];break b}a<<=6;a|=Og[g-32]-1;d+=6;8<=d&&(e.push(a>>d-8&255),d-=8)}m=e}a=m;m={};m.Oa=Array(4);m.buffer=Array(4);m.Lk=Array(4);m.padding=
Array(64);m.padding[0]=128;for(e=1;64>e;++e)m.padding[e]=0;Pg(m);e=Array(64);64<a.length&&(Pg(m),Qg(m,a),a=Rg(m));for(d=0;d<a.length;++d)e[d]=a[d]^92;for(d=a.length;64>d;++d)e[d]=92;Pg(m);for(d=0;64>d;++d)m.buffer[d]=e[d]^106;Sg(m,m.buffer);m.total=64;Qg(m,Tg(n));n=Rg(m);Pg(m);Sg(m,e);m.total=64;Qg(m,n);n=Rg(m);n=n.slice(0,8);wa(n)&&(n=Tg(n));m="";if(n){e=n.length;for(f=d=a=0;e--;)for(d<<=8,d|=n[f++],a+=8;6<=a;)m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(d>>a-6&63),a-=6;a&&(m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(d<<8>>a+8-6&63))}n=m}else n="";c={oq:c,gs_l:b+"."+n};this.H.nj&&(c.q=this.R.o);return c};p.reset=function(){this.T=Ha();++this.ma;var a=this.R;a.ra=0;a.ua=0;a.Aa=0;this.ha.reset();a=this.o;a.R&&a.H.R();a.Ua=0;a.W=0;a.ya=0;a.va=0;a.Ya=0;a.wa=0;a.Aa=0;a.ra=0;a.ua=0;a.ta=[];for(var b=0;b<=Ng;++b)a.ta[b]=0;for(a=0;b=this.ra[a++];)b.reset()};p.setToken=aa("W");function Mg(a){return a?a.replace(Jg,"-"):""}
;function Ug(){this.w=121}
w(Ug,J);p=Ug.prototype;p.Pb=function(a){this.S=a.Bc()};p.Qa=function(a){this.H=a.get(347);this.W=a.get(130);this.ra=a.get(117);this.ka=a.get(123);this.T=a.get(118);this.ta=a.get(120);this.ua=a.get(128);this.ma=a.get(139);this.ha=a.T;this.V=a.o[294]||[]};p.activate=aa("R");p.search=function(a,b){if(this.V){for(var c=!1,d=0,e;e=this.V[d++];)2==e.o(a,b)&&(c=!0);if(c)return}if(Ge(a)||this.R.Zb||this.W&&this.W.Zb()){if(me.test(b)){if(this.S&&!this.o){c=this.S;b:{if(d=c.getElementsByTagName("input")){e=0;for(var f;f=d[e++];)if("btnI"==f.name&&"submit"!=f.type.toLowerCase()){d=f;break b}}d=null}d?c=null:(d=qf("input"),d.type="hidden",d.name="btnI",d.value="1",c.appendChild(d),c=d);this.o=c}}else this.o&&(this.S.removeChild(this.o),this.o=null);this.H&&this.R.sf&&this.H.o(b);this.ha.search(a,b);Vg(this);Of(this.ra,12,{query:a})}};p.redirect=function(a){this.H&&this.R.sf&&this.H.o(void 0);this.ha.redirect(a);Vg(this)};function Vg(a){var b=a.ka;b.V=b.S;a.ka.o=null;a.ta.reset();a.ua.clear();a.T.S!=a.T.o&&(b=a.T,b.S=b.o);a.ma&&a.ma.clear()}
;function Wg(){this.w=553}
w(Wg,J);Wg.prototype.Qa=function(a){this.o=a.o[156]||[];a.get(126)};Wg.prototype.setup=function(){this.o.sort(Xg)};Wg.prototype.activate=function(a){this.R=a;this.H=a.Rj};function $f(a,b,c){b=new Qe(b,c||Ee(b.length));c=1;if(a.o)for(var d=0,e;e=a.o[d++];)e=["productId:"+e.o].join("|"),e.length&&Se(b,"requiredfields",e,!0),1>c&&(c=1);b.V=c;Se(b,"ds",a.R.hf,!0);Se(b,"pq",a.H,!0);if(!b.R){b.T=Ha();"cp"in b.H||(a=b.ma.od(),Se(b,"cp",a,!0));Se(b,"gs_id",b.w);a=b.H;c=[];for(var f in a)Fe(f,a[f],c,void 0);b.R=!0}return b}
function Xg(){return 0}
;function Yg(){this.w=123;this.ha=!1;this.S=-1}
w(Yg,J);var Zg=[0,1,2,3,4,5,5,6,6,6,7,7,7,7,7,8,8,8,8,8],Ng=Zg[Zg.length-1]+1,$g=100*Zg.length-1;p=Yg.prototype;p.Qa=function(a){this.H=a.get(133);this.Fa=a.get(130);this.Wb=a.get(118);this.Xb=a.get(120);this.Vb=a.get(494);this.Eb=a.get(124);this.Ca=a.get(125);this.Da=a.get(230);this.Yb=a.get(127)};p.activate=function(a){this.Sa=this.Yb.H;this.Ia=a;this.ha=!0;this.T={};this.ma=0;this.mb=a.ki;this.wb=a.dj;this.V=-1;this.R=this.Ia.Rh&&!!this.H};p.deactivate=function(){this.ha=!1;ah(this);this.T=this.o=null;this.V=this.S};function ag(a,b){if(!(!a.ha||a.wb||a.Fa&&a.Fa.w())){var c=!0,d=Re(b);d>a.S&&(a.S=d);++a.Ua;d=a.Vb;d.o[b.getId()]=!0;Ge(b.o)||(d.R=0);d=Ha();for(var e in a.T)2500<d-a.T[e].T&&bh(a,e);a.R&&(e=a.H.get(b))&&((c=a.mb||!1)&&a.Ia.ej&&(b.S=!0),a.Ca.uc(e),e.S&&++a.ya,a.o=null);c&&(a.o=b,a.ka||a.lg())}}
function ch(a,b){return t(function(a){this.Cg(a,b)},a)}
p.lg=function(){ah(this);if(this.o){var a=[],b=this.o.getParameters();if(b)for(var c in b)Fe(c,b[c],a);var d=this.o,e=a.join("&");a=ch(this,this.o);b=t(this.Cg,this);c=this.Sa;var f=d.getId(),g=d.o;c.H.tf||Ff(c);d=c.V+c.T+c.ma+"?"+(c.ha?c.ha+"&":"")+(e?e+"&":"");e=[];Fe("q",g,e,!0);c.H.$g||Fe("callback","google.sbox.p"+c.W,e);if(c.ka){g="";for(var l=4+Math.floor(32*Math.random()),m=0,n;m<l;++m)n=.3>Math.random()?48+Math.floor(10*Math.random()):(.5<Math.random()?65:97)+Math.floor(26*Math.random()),g+=String.fromCharCode(n);Fe("gs_gbg",g,e)}g=td();d+=e.join("&");d=ud(d);g.src=ed(d);g.charset="utf-8";c.o[f]=g;c.S=c.H.tf?b:a;c.R.appendChild(g);this.o.S||(++this.va,a=this.o,this.T[a.getId()]=a,++this.W);this.o=null;a=100;b=(this.W-2)/2;for(c=1;c++<=b;)a*=2;a<this.ma&&(a=this.ma);this.ka=window.setTimeout(t(this.lg,this),a)}};function ah(a){null!=a.ka&&(window.clearTimeout(a.ka),a.ka=null)}
function bh(a,b){var c=a.Sa,d=c.o[b];d&&(c.R.removeChild(d),delete c.o[b]);delete a.T[b];a.W&&--a.W}
p.Cg=function(a,b){if(this.ha){if(!b&&(b=this.T[(a[2]||{}).j],!b))return;if(!b.S){var c=this.Eb;var d=b,e=a[0],f=a[1],g={};if(a=a[2])for(var l in a){var m=a[l];l in c.o&&(m=c.o[l].parse(m));g[l]=m}var n=m=!1;l=!1;a=0;for(var u;u=f[a++];)if(33==(u[1]||0)?n=!0:m=!0,n&&m){l=!0;break}m=0;n=[];for(a=0;u=f[a++];){var D=u[1]||0;if(!l||33!=D){var z=u[0];c.H&&(z=dh(e.toLowerCase(),Ie(z).replace(we,"")));n.push(new qe(z,Ie(z).replace(we,""),m++,D,u[2]||[],eh(u)))}}c=new Te(d,n,new oe(g),!1,!0);this.Da&&(c=
this.Da.o(c,this.Wb.o));this.R&&this.H.H(c);Re(b)<=this.V||(++this.wa,this.Ca.uc(c)||++this.Aa,this.ma=c.getParameters().o.d||0,b&&(bh(this,b.getId()),b=b.T,b=Ha()-b,this.ua+=b,this.ra=Math.max(b,this.ra),++this.ta[b>$g?Ng:Zg[Math.floor(b/100)]]));c&&(b=c.getParameters().Wa("q"))&&this.Xb.setToken(b)}}};function fh(){this.w=124;this.o={}}
w(fh,J);fh.prototype.Qa=function(a){a.get(150);a=a.o[158]||[];for(var b=0,c;c=a[b++];)this.o[c.ln()]=c};fh.prototype.activate=function(a){this.H=a.Oi};function eh(a){return(a=a[3])?new oe(a):pe}
;function gh(){this.w=125}
w(gh,J);gh.prototype.Qa=function(a){this.S=a.get(117);this.V=a.get(118);this.T=a.get(494);this.o=a.o[122]||[];this.R=a.get(126);this.H=a.get(128);this.o.sort(hh)};gh.prototype.uc=function(a){var b=this.V.o.toLowerCase();if(b==a.o.o.toLowerCase())b=!0;else{var c=a,d=this.R.o;b=Je(b);var e=c.o;c=e?e.W:Je(c.o.o.toLowerCase());d=d?d.o.W:"";b=0==b.indexOf(c)?0==b.indexOf(d)?c.length>=d.length:!0:!1}if(b){if(this.o)for(d=0;c=this.o[d++];)a=Bf(c,a);c=this.R.o=a;a=c.o.o;d=c.w;if(this.H.Ca)if(d.length){var f=0==c.Ga();e=this.H;var g=!1,l=e.ra&&e.ra.H(d);e.clear();if((e.H=d)&&d.length){g=d[0].o;a:{var m=g;if(e.ya.o){for(var n=!1,u=!1,D=0,z;D<m.length;++D)if(z=m.charAt(D),!vg.test(z)&&(ug.test(z)?u=!0:n=!0,u&&n)){m=!0;break a}m=!1}else m=!0}m&&(g=e.W.S);e.ha=gg(e.ya,g);if(f){e.ka=!0;g=e.S;if(g.S){g.ma=e.ha;ih(g);f=!1;for(m=0;n=d[m++];)jh(g,n)&&(f=!0);g=f}else g=!1;m=d[0].getParameters().Wa("a");m=Ie(m);f=e.Da;n=0;if(m){f.o||(n=rf(f.V.Pf),u=n.style,u.background="transparent",u.color="#000",u.padding=0,u.position="absolute",u.whiteSpace="pre",f.o=n,f.o.style.visibility="hidden",f.T.appendChild(f.o));n=Ha();if(!f.R||f.R+3E3<n)f.R=n,n=f.o,u=uf(n),n=(n=u.getComputedStyle?u.getComputedStyle(n,""):n.currentStyle)?n.fontSize:null,f.S&&n==f.S||(f.H={},f.S=n);m in f.H?n=f.H[m]:(n=f.o,u=He(m),n.innerHTML!=u&&(n.innerHTML=u),f.H[m]=n=f.o.offsetWidth,f=f.o,""!=f.innerHTML&&(f.innerHTML=""))}e.va=n}else e.ka=!1,g=e.S.render(pg(e),e.ha),e.va=0;l&&(e.R=e.ra.w(),jg(e,e.ra.o()));g?e.show():e.clear()}g&&(e=this.T,g=c.o,l=g.getId(),l in e.o&&(Ge(g.o)||(e.R=c.w.length),c=g.T,c=Ha()-c,e.H+=c,++e.S,delete e.o[l]))}else this.H.clear();Of(this.S,3,{input:a,wk:d})}return b};function hh(){return 0}
;function kh(){this.w=126}
w(kh,J);kh.prototype.Qa=function(a){this.H=a.get(123)};kh.prototype.activate=function(){this.o=null};function lh(){this.w=127;this.o={}}
w(lh,J);lh.prototype.Qa=function(a){a=a.o[149]||[];for(var b=0,c;c=a[b++];)this.o[0]=c};lh.prototype.activate=function(a){var b="https:"==document.location.protocol,c=[];Fe("client",a.Ld,c);Fe("hl",a.je,c);Fe("gl",a.Qg,c);Fe("sugexp",a.Sg,c);Fe("gs_rn",55,c);Fe("gs_ri",a.we,c);a.authuser&&Fe("authuser",a.authuser,c);this.R={protocol:"http"+(b?"s":"")+"://",host:a.tg||"clients1."+a.Lh,ve:a.ve||"/complete/search",tk:c.length?c.join("&"):""};this.H&&0==a.Nd||(this.H=this.o[a.Nd])};function mh(){this.w=191}
w(mh,J);var Og=[0,0,0,0,0,0,0,0,0,0,0,0,0,63,0,0,53,54,55,56,57,58,59,60,61,62,0,0,0,0,0,0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,0,0,0,0,64,0,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,0,0,0,0,0],nh=[7,12,17,22,7,12,17,22,7,12,17,22,7,12,17,22,5,9,14,20,5,9,14,20,5,9,14,20,5,9,14,20,4,11,16,23,4,11,16,23,4,11,16,23,4,11,16,23,6,10,15,21,6,10,15,21,6,10,15,21,6,10,15,21],oh=[3614090360,3905402710,606105819,3250441966,4118548399,1200080426,2821735955,4249261313,1770035416,2336552879,4294925233,2304563134,1804603682,4254626195,2792965006,1236535329,4129170786,3225465664,643717713,3921069994,3593408605,38016083,3634488961,3889429448,568446438,3275163606,4107603335,1163531501,2850285829,4243563512,1735328473,2368359562,4294588738,2272392833,1839030562,4259657740,2763975236,1272893353,4139469664,3200236656,681279174,3936430074,3572445317,76029189,3654602809,3873151461,530742520,3299628645,4096336452,1126891415,2878612391,4237533241,1700485571,2399980690,4293915773,2240044497,1873313359,4264355552,2734768916,1309151649,4149444226,3174756917,718787259,3951481745];function Tg(a){for(var b=[],c=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(b[c++]=e>>12|224,b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b}
function Pg(a){a.Oa[0]=1732584193;a.Oa[1]=4023233417;a.Oa[2]=2562383102;a.Oa[3]=271733878;a.Vc=a.total=0}
function Sg(a,b){for(var c=a.Lk,d=0;64>d;d+=4)c[d/4]=b[d]|b[d+1]<<8|b[d+2]<<16|b[d+3]<<24;var e=a.Oa[0];b=a.Oa[1];d=a.Oa[2];for(var f=a.Oa[3],g,l,m,n=0;64>n;++n)16>n?(g=f^b&(d^f),l=n):32>n?(g=d^f&(b^d),l=5*n+1&15):48>n?(g=b^d^f,l=3*n+5&15):(g=d^(b|~f),l=7*n&15),m=f,f=d,d=b,e=e+g+oh[n]+c[l]&4294967295,g=nh[n],b=b+((e<<g|e>>>32-g)&4294967295)&4294967295,e=m;a.Oa[0]=a.Oa[0]+e&4294967295;a.Oa[1]=a.Oa[1]+b&4294967295;a.Oa[2]=a.Oa[2]+d&4294967295;a.Oa[3]=a.Oa[3]+f&4294967295}
function Qg(a,b,c){c||(c=b.length);a.total+=c;for(var d=0;d<c;++d)a.buffer[a.Vc++]=b[d],64==a.Vc&&(Sg(a,a.buffer),a.Vc=0)}
function Rg(a){var b=Array(16),c=8*a.total,d=a.Vc;Qg(a,a.padding,56>d?56-d:64-(d-56));for(var e=56;64>e;++e)a.buffer[e]=c&255,c>>>=8;Sg(a,a.buffer);for(e=d=0;4>e;++e)for(c=0;32>c;c+=8)b[d++]=a.Oa[e]>>c&255;return b}
;function ph(){this.w=150}
w(ph,J);function dh(a,b){b=He(b.replace(ne,""));a=He(Je(a,!0));if(Ke(b,a))return a+"<b>"+b.substr(a.length)+"</b>";for(var c="",d=[],e=b.length-1,f=0,g=-1,l;l=b.charAt(f);++f)" "==l||"\t"==l?c.length&&(d.push({t:c,s:g,e:f+1}),c="",g=-1):(c+=l,-1==g?g=f:f==e&&d.push({t:c,s:g,e:f+1}));a=a.split(/\s+/);f={};for(c=0;e=a[c++];)f[e]=1;g=-1;a=[];l=d.length-1;for(c=0;e=d[c];++c)f[e.t]?(e=-1==g,c==l?a.push({s:e?c:g,e:c}):e&&(g=c)):-1<g&&(a.push({s:g,e:c-1}),g=-1);if(!a.length)return"<b>"+b+"</b>";c="";for(f=e=0;g=
a[f];++f)(l=d[g.s].s)&&(c+="<b>"+b.substring(e,l-1)+"</b> "),e=d[g.e].e,c+=b.substring(l,e);e<b.length&&(c+="<b>"+b.substring(e)+"</b> ");return c}
;function qh(){this.w=146}
w(qh,J);function rh(a){JSON.parse('"\\u30'+a.split(",").join("\\u30")+'"')}
rh("02,0C,0D,01,FB,F2,A1,A3,A5,A7,A9,E3,E5,E7,C3,FC,A2,A4,A6,A8,AA,AB,AD,AF,B1,B3,B5,B7,B9,BB,BD,BF,C1,C4,C6,C8,CA,CB,CC,CD,CE,CF,D2,D5,D8,DB,DE,DF,E0,E1,E2,E4,E6,E8,E9,EA,EB,EC,ED,EF,F3,9B,9C");rh("F4__,AC,AE,B0,B2,B4,B6,B8,BA,BC,BE,C0,C2,C5,C7,C9_____,D0,D3,D6,D9,DC");rh("D1,D4,D7,DA,DD");rh("F4____,AC_,AE_,B0_,B2_,B4_,B6_,B8_,BA_,BC_,BE_,C0_,C2__,C5_,C7_,C9______,D0__,D3__,D6__,D9__,DC");rh("D1__,D4__,D7__,DA__,DD");rh("A6,AB,AD,AF,B1,B3,B5,B7,B9,BB,BD,BF,C1,C4,C6,C8,CF,D2,D5,D8,DB");rh("CF,D2,D5,D8,DB");function sh(){this.w=116;this.ya=!0}
w(sh,J);p=sh.prototype;p.Pb=function(a,b){this.Ca=a.$d();b.addRule(".sbdd_a",(kf?"margin-top:-1px;":"")+"z-index:989");b.addRule(".sbdd_a[dir=ltr] .fl, .sbdd_a[dir=rtl] .fr","float:left");b.addRule(".sbdd_a[dir=ltr] .fr, .sbdd_a[dir=rtl] .fl","float:right");kf?b.addRule(".sbdd_b","background:#fff;border:1px solid #ccc;border-top-color:#d9d9d9;"+b.prefix("border-radius:0 0 3px 3px;")+b.prefix("box-shadow:0 2px 1px rgba(0,0,0,.1), 0 0 1px rgba(0,0,0,.1);")+"cursor:default"):b.addRule(".sbdd_b","border:1px solid #ccc;border-top-color:#d9d9d9;"+b.prefix("box-shadow:0 2px 4px rgba(0,0,0,0.2);")+
"cursor:default");b.addRule(".sbdd_c","border:0;display:block;position:absolute;top:0;z-index:988")};p.Qa=function(a){this.Aa=a.get(130);a.get(115);this.V=a.get(118);this.ua=a.get(117);this.Fa=a.S.getId()};p.setup=aa("o");p.ad=function(a){this.H=rf();this.H.className="gstl_"+this.Fa+" sbdd_a";Mf(this.H,!1);this.va=this.H;this.ma=rf("fl");this.H.appendChild(this.ma);this.ha=rf();this.H.appendChild(this.ha);this.T=rf("sbdd_b");this.ha.appendChild(this.T);this.Ia=rf();this.ha.appendChild(this.Ia);this.o.Ni&&(this.R=qf("iframe","gstl_"+this.Fa+" sbdd_c"),Mf(this.R,!1),(this.o.nb||document.body).appendChild(this.R));if(this.S=this.o.Oh)xa(this.S)&&(this.S+=this.o.jd[2],this.S-=th(this)),uh(this,this.H,this.S);vh(this);(a.nb||document.body).appendChild(this.H);a=this.ua;var b=t(this.Bg,this);yg(a,a.H,8,b,void 0,void 0)};p.activate=function(a){this.o=a;this.H.style.position=a.kd};p.show=function(a){Nf(this,a.$b||this.Ca);var b=a.marginWidth;if(this.Da!=b){var c=this.ma.style;b?(c.width=b+"px",c.height="1px"):c.height="";this.Da=b}this.ya=a.mj;this.wa=a.Nf;Lf(this.V.R,!0);Mf(this.va,!0);Mf(this.R,!0);Of(this.ua,14);this.Bg()};p.Bg=function(){this.ka=0;vh(this);if(this.R){var a=this.o.Gh[0],b=this.R.style;"relative"!=this.o.kd&&(b.top=this.H.style.top,b.left=this.H.offsetLeft+this.ma.offsetWidth+"px");b=this.R;this.ka||(this.ka=this.T?Math.max(this.T.offsetHeight,0):0);b.style.height=Math.max(this.ka+a,0)+"px";uh(this,this.R,this.T.offsetWidth)}this.W&&ih(this.W.o)};function vh(a){var b,c;if(c=a.W)c=a.W.o,c=c.o.Qi||c.ra==c.ma?c.Fa:null;var d=(b=c)?b.offsetWidth:wh(a.V.R);var e=a.S;c=th(a);e?wa(e)&&(e=null):a.Da||!a.ya?a.ha.style.display="inline-block":(a.ha.style.display="",e=d+a.o.jd[2]-c,uh(a,a.H,e));if("relative"!=a.o.kd){var f="rtl"==le()!=("rtl"==a.ta),g=a.o.nb;var l={Ib:0,Cd:0};if(f||!g||g==document.body||a.o.vf)l=nf(a.V.R.ka),b&&(l.Ib=nf(b).Ib);b=l;l=e;e=a.o.jd;g=e[1];var m=a.V.R,n=m.ka?m.ka.offsetHeight:0;m.ua>n&&(n=m.ua);e=b.Cd+n+e[0];if("right"==a.wa){l=
"rtl"==le()!=("rtl"==a.ta);m=a.o.nb;g=-g;if(l||!m||m==document.body)g+=(uf(a.H)||window).document.documentElement.clientWidth-d-b.Ib;d=g;l=e;b=void 0}else b=b.Ib+g,"center"==a.wa&&l&&(b+=(d-l)/2),l=e,d=void 0;e={Ib:0,Cd:0};"absolute"==a.o.kd&&a.o.nb&&a.o.nb!=document.body&&(f||a.o.vf)&&(e=nf(a.o.nb));g=a.H.style;g.top=l-e.Cd+"px";g.left=g.right="";void 0!=b?g.left=b+c-e.Ib+"px":(b=0,a.o.nb&&f&&(b=document.body.clientWidth-(e.Ib+a.o.nb.offsetWidth)),g.right=d+c-b+"px")}}
function uh(a,b,c){xa(c)?0<c&&(a.o.ah?b.style.width=c+"px":b.style.minWidth=c+"px"):b.style.width=c}
function Mf(a,b){a&&(a.style.display=b?"":"none")}
function Nf(a,b){if(a.ta!=b){a.ta=b;var c=a.o.nb;c&&c!=document.body&&(c.style.textAlign="rtl"==b?"right":"left");sf(a.H,b)}}
function th(a){return a.Aa&&a.Aa.H()&&(a=a.V.R.W.offsetWidth,xa(a))?a:0}
;function xh(){this.w=119;this.wa=!1;this.V=Ee(0);this.Ca=-1;this.Da=!1}
w(xh,J);p=xh.prototype;p.Pb=function(a,b){this.ma=a;this.o=a.vi();this.o.setAttribute("aria-haspopup",!1);this.o.setAttribute("role","combobox");this.o.setAttribute("aria-autocomplete","both");a.Dh()||(b.addRule(".sbib_a","background:#fff;"+b.prefix("box-sizing:border-box;")),b.addRule(".sbib_b",b.prefix("box-sizing:border-box;")+"height:100%;overflow:hidden;padding:4px 6px 0"),b.addRule(".sbib_c[dir=ltr]","float:right"),b.addRule(".sbib_c[dir=rtl]","float:left"),b.addRule(".sbib_d",b.prefix("box-sizing:border-box;")+"height:100%;unicode-bidi:embed;white-space:nowrap"),b.addRule(".sbib_d[dir=ltr]","float:left"),b.addRule(".sbib_d[dir=rtl]","float:right"),bf&&b.addRule(".sbib_a input::-ms-clear","display: none"),b.addRule(".sbib_a,.sbib_c","vertical-align:top"))};p.Qa=function(a){this.H=a.get(118);this.R=a.get(117);this.Fa=a.get(128);this.ta=a.get(173);this.Ua=!!a.get(136);this.Eb=a.S.getId()};p.setup=function(a){this.ra=a;this.ua=a.ij;this.va=a.jj;this.wb=a.Uh;this.T=of(this.o);this.Dd();var b=this;af&&yg(this.R,this.o,"beforedeactivate",function(a){b.Da&&(b.Da=!1,a.vd=!0)},10);cf&&yh(this);this.ka=this.o};p.ad=function(a){var b=!!a.Vh[130];if(this.Ua||eg(this.H)||b||a.mi)(this.S=this.ma.get("gs_id"))?(b&&(this.W=this.ma.get("sb_chc")),this.ha=this.ma.get("sb_ifc")):(this.S=rf("gstl_"+this.Eb+" sbib_a"),a=this.S.style,this.va&&(a.width=this.va+"px"),this.ua&&(a.height=this.ua+"px"),a=this.o.style,a.border="none",a.padding=df||af?"0 1px":"0",a.margin="0",a.height="auto",a.width="100%",this.o.className=this.ra.Pf,b&&(this.W=rf("sbib_d"),this.W.id=this.ma.getId("sb_chc"),this.S.appendChild(this.W)),eg(this.H)&&
this.ta&&(this.ta.o().className+=" sbib_c",this.S.appendChild(this.ta.o())),this.ha=rf("sbib_b"),this.ha.id=this.ma.getId("sb_ifc"),this.S.appendChild(this.ha),zh(this,this.S,this.ha)),jf&&ef&&(this.o.style.height="1.25em",this.o.style.marginTop="-0.0625em"),Ah(this,this.S),this.ka=this.S;this.wb&&(b=t(this.kg,this),yg(this.R,this.o,"blur",b,10),b=t(this.wg,this),yg(this.R,this.o,"focus",b,10),this.mb=!0);b=this.R;a=t(this.Li,this);yg(b,b.H,8,a,void 0,void 0);Bh(this)};p.activate=function(a){this.ra=a;var b=a.hj;b&&this.ma.xf(b);this.o.setAttribute("autocomplete","off");this.o.setAttribute("spellcheck",!1);this.o.style.outline=a.Ij?"":"none";this.mb&&this.wg();Ch(this)};p.deactivate=function(){this.mb&&this.kg();Dh(this)};function zh(a,b,c){Dh(a);c||(c=b);a.o.parentNode.replaceChild(b,a.o);c.appendChild(a.o);a.T&&a.ra.Vj&&(af||cf?Sf(a.R,function(){a.o.focus();mf(a.o,a.V.od())}):a.o.focus());Ch(a)}
function wh(a){return a.va?a.va:a.ka?a.ka.offsetWidth:0}
p.select=function(){this.o.select();this.Dd()};function dg(a){hf&&(a.o.value="");a.o.value=a.H.o;hf&&(a.o.value=a.o.value);Eh(a)}
p.focus=function(){if(!this.T)try{this.o.focus(),this.T=!0,Eh(this)}catch(a){}};p.clear=function(){this.o.value=""};function Eh(a){if(a.T){var b=a.o.value.length;a.V=Ee(b);mf(a.o,b)}}
function Ah(a,b){yg(a.R,b,"mouseup",function(){a.o.focus()})}
function Bh(a){function b(b){yg(a.R,a.o,b,t(a.rg,a),10,c)}
yg(a.R,a.o,"keydown",t(a.Ji,a));(df||a.ra.Hh)&&yg(a.R,a.o,"keypress",t(a.Ki,a));yg(a.R,a.o,"select",t(a.Dd,a),10);var c=!1;b("mousedown");b("keyup");b("keypress");c=!0;b("mouseup");b("keydown");b("focus");b("blur");b("cut");b("paste");b("input");var d=t(a.Fi,a);yg(a.R,a.o,"compositionstart",d);yg(a.R,a.o,"compositionend",d)}
p.Fi=function(a){a=a.type;"compositionstart"==a?(a=this.H,1!=a.ha&&(a.ha=!0)):"compositionend"==a&&(a=this.H,0!=a.ha&&(a.ha=!1))};p.Ji=function(a){var b=a.keyCode;this.Ca=b;var c=(ef||cf)&&(38==b||40==b)&&Uf(this.Fa),d=13==b,e=27==b;this.Aa=!1;9==b&&(this.Aa=Tf(this.H));if(d){(b=Vf(this.Fa))&&b.Ga();var f=this;Sf(this.R,function(){var b=f.Fa,c=a.shiftKey?4:3;null!=b.R&&Vf(b).Ga();b.W.search(c)})}if(c||d||e||this.Aa)a.vd=!0};p.Ki=function(a){var b=a.keyCode,c=9==b&&this.Aa;if(13==b||27==b||c)a.vd=!0};p.rg=function(a){if(!this.Ya){var b=a.Nc;if(!(b.indexOf("key")||a.ctrlKey||a.altKey||a.shiftKey||a.metaKey))a:if(a=a.keyCode,"keypress"!=b){var c=38==a||40==a;if("keydown"==b){var d=this.H;var e=229==a;(d.ta=e)&&d.ma.add(4);if(c)break a}else if(d=a!=this.Ca,this.Ca=-1,!c||d)break a;switch(a){case 27:a=this.H;a.T.hk?a.search(5):(a.H.Bb()?a.H.bc():bg(a),cg(a));break;case 37:fg(this.H,"rtl");break;case 39:fg(this.H,"ltr");break;case 38:this.H.H.Ag();break;case 40:a=this.H;c=this.V;Uf(a.H)?a.H.zg():Yf(a.H,c);break;case 46:a=this.H;a.o&&this.V.Cf()==a.o.length&&(a.ya&&a.ya.clear(),a.T.fk&&a.search(2));break;case 8:a=this.H,a.ka&&0==this.V.od()&&a.ka.o()}}this.Dd();Wf(this.H,this.o.value,this.V,b)}};p.Ei=function(){this.T=!0;Of(this.H.V,10)};p.Bi=function(){this.T=!1;Rf(this.H)};function Ch(a){a.wa||(a.wa=!0,a.Sa=t(a.Ei,a),yg(a.R,a.o,"focus",a.Sa,99),a.Ia=t(a.Bi,a),yg(a.R,a.o,"blur",a.Ia,99))}
function Dh(a){a.wa&&(a.wa=!1,Cg(a.R,a.o,a.Sa),Cg(a.R,a.o,a.Ia))}
p.wg=function(){if(!this.ya){var a=this.ra.Qj||50;this.ya=window.setInterval(t(this.Pj,this),a)}};p.kg=function(){this.ya&&(window.clearTimeout(this.ya),this.ya=null)};p.Pj=function(){this.rg({Nc:"polling"})};p.Li=function(){if(cf){var a=this.o,b=document.createEvent("KeyboardEvent");b.initKeyEvent&&(b.initKeyEvent("keypress",!0,!0,null,!1,!1,!0,!1,27,0),a.dispatchEvent(b))}};p.Dd=function(){if(this.T){a:{var a=this.o;try{if("selectionStart"in a){var b=a.selectionStart;var c=a.selectionEnd}else{var d=a.createTextRange(),e=pf(a).selection.createRange();d.inRange(e)&&(d.setEndPoint("EndToStart",e),b=d.text.length,d.setEndPoint("EndToEnd",e),c=d.text.length)}if(void 0!==b){var f=Ee(b,c);break a}}catch(g){}f=null}f&&(this.V=f)}};function yh(a){var b;Dg(window,"pagehide",function(){a.Ya=!0;b=a.o.value});Dg(window,"pageshow",function(c){a.Ya=!1;if(c.persisted||void 0!==b){c=a.H;var d=b;Zf(c,d);dg(c.R);Of(c.V,4,{$b:c.W,input:d})}})}
function Lf(a,b){a.o.setAttribute("aria-haspopup",b);b||a.o.removeAttribute("aria-activedescendant")}
;function Fh(a){if(a.classList)return a.classList;a=a.className;return wa(a)&&a.match(/\S+/g)||[]}
function rg(a,b){a.classList?b=a.classList.contains(b):(a=Fh(a),b=0<=mc(a,b));return b}
function Gh(a,b){a.classList?a.classList.remove(b):rg(a,b)&&(a.className=oc(Fh(a),function(a){return a!=b}).join(" "))}
;function Hh(){this.w=129;this.ta={};this.ua=[];this.wa=[];this.Ca=[];this.ha=[];this.Da=0}
w(Hh,J);p=Hh.prototype;p.Pb=function(a,b){this.Ia=a;this.ra=a.$d();kf||b.addRule(".sbsb_a","background:#fff");b.addRule(".sbsb_b","list-style-type:none;margin:0;padding:0");kf||b.addRule(".sbsb_c","line-height:22px;overflow:hidden;padding:0 7px");b.addRule(".sbsb_d","background:#eee");b.addRule(".sbsb_e","height:1px;background-color:#e5e5e5");b.addRule("#sbsb_f","font-size:11px;color:#36c;text-decoration:none");b.addRule("#sbsb_f:hover","font-size:11px;color:#36c;text-decoration:underline");b.addRule(".sbsb_g","text-align:center;padding:8px 0 7px;position:relative");b.addRule(".sbsb_h","font-size:15px;height:28px;margin:0.2em"+(ef?";-webkit-appearance:button":""));b.addRule(".sbsb_i","font-size:13px;color:#36c;text-decoration:none;line-height:100%");b.addRule(".sbsb_i:hover","text-decoration:underline");b.addRule(".sbsb_j","padding-top:1px 0 2px 0;font-size:11px");b.addRule(".sbdd_a[dir=ltr] .sbsb_j","padding-right:4px;text-align:right");b.addRule(".sbdd_a[dir=rtl] .sbsb_j","padding-left:4px;text-align:left");kf&&(b.addRule(".sbsb_c[dir=ltr] .sbsb_k","padding:10px 3px 11px 8px"),b.addRule(".sbsb_c[dir=rtl] .sbsb_k","padding:10px 8px 11px 3px"))};p.Qa=function(a){this.ka=a.get(128);this.R=a.get(118);this.Aa=a.get(121);a=a.o[152]||[];var b={};if(a)for(var c=0,d;d=a[c++];)b[d.S]=d;this.ya=b};p.setup=aa("o");p.ad=function(){this.S=rf();this.T=qf("ul","sbsb_b");this.T.setAttribute("role","listbox");this.S.appendChild(this.T)};p.activate=function(a){this.o=a;var b=a.qg;b&&(this.Fa=this.Ia.xf(b));this.S.className=a.yk||"sbsb_a";this.va=a.vk||"sbsb_d"};p.render=function(a,b){if(!this.S)return!1;this.ma=b;ih(this);b=!1;for(var c=0,d;d=a[c++];)if(1==d)if(this.W)this.W.style.display="";else{d=rf();var e=d.style;e.position="relative";e.textAlign="center";e.whiteSpace="nowrap";d.dir=this.ra;this.H=rf();this.H.className="sbsb_g";this.o.Kf&&(this.H.style.paddingBottom="1px");Ih(this,this.o.ik,this.H,13);this.o.Si?Ih(this,this.o.hi,this.H,8):this.o.Vi&&Ih(this,this.o.kk,this.H,14);d.appendChild(this.H);d.onmousedown=t(this.te,this);d.className=this.o.Ke;this.W=d;this.S.appendChild(this.W)}else 2==d?this.V?this.V.style.display="":(d=rf("sbsb_j "+this.o.Ke),e=qf("a"),e.id="sbsb_f",e.href="http://www.google.com/support/websearch/bin/answer.py?hl="+this.o.je+"&answer=106230",e.innerHTML=this.o.sj,d.appendChild(e),d.onmousedown=t(this.te,this),this.V=d,this.S.appendChild(this.V)):3==d?(d=this.Ca.pop(),d||(d=qf("li"),d.o=!0,e=qf("div","sbsb_e"),d.appendChild(e)),this.T.appendChild(d)):jh(this,d)&&(b=!0);return b};function mg(a,b){(b=a.ha[b])&&Gh(b.w.parentNode,a.va)}
p.clear=function(){for(var a,b,c;c=this.ua.pop();)a=c.Ga(),(b=this.ta[a])||(b=this.ta[a]=[]),b.push(c),a=c.w,a.parentNode.removeChild(a);for(;a=this.T.firstChild;)a=this.T.removeChild(a),a.o?this.Ca.push(a):a!=this.W&&a!=this.V&&this.wa.push(a);this.W&&(this.W.style.display="none");this.V&&(this.V.style.display="none");this.ha=[]};function jh(a,b){var c=b.Ga(),d=a.ya[c];if(!d)return!1;c=(c=a.ta[c])&&c.pop();if(!c){c=d.H();var e=c.w;e.setAttribute("role","option");e.id="sbse"+a.Da;a.Da++}d.render(b,c);a.ua.push(c);e=c.w;var f=Jh(a);f.appendChild(e);if(void 0!==b.T){a.ha.push(c);var g=a.ma;var l=b.H;a.o.bj&&(e.onmouseover=function(){jg(a.ka,l)},e.onmouseout=function(){og(a.ka)});var m=c.w;m.onclick=function(c){bg(a.R);b.w&&Xf(a.R,b.o);og(a.ka);var e=a.ka;e.R=e.o=l;c=c||uf(m).event;d.o(c,b,a.Aa)}}else g=a.ra;sf(f,g);return!0}
function Ih(a,b,c,d){var e=qf("input");e.type="button";e.value=Ie(b);e.onclick=function(){a.Aa.search(a.R.o,d)};if(a.o.Pi){b="lsb";var f=qf("span");var g=qf("span");f.className="ds";g.className="lsbb";f.appendChild(g);g.appendChild(e)}else b="sbsb_h",f=e;e.className=b;c.appendChild(f)}
function Jh(a){var b=a.wa.pop();if(b)return a.T.appendChild(b),b;b=qf("li");b.className="sbsb_c "+a.o.Ke;b.onmousedown=t(a.te,a);a.T.appendChild(b);return b}
p.te=function(a){a=a||uf(this.S).event;a.stopPropagation?a.stopPropagation():!df&&af&&(this.R.R.Da=!0);return!1};function ih(a){if(a.H){var b=0,c=a.R.R.W;c&&(b=c.offsetWidth);b=wh(a.R.R)-b-3;0<b&&(a.H.style.width=b+"px")}}
;function Kh(){this.w=147}
w(Kh,J);Kh.prototype.Pb=function(a){this.T=a.Bc()||document.body};Kh.prototype.setup=aa("V");function Lh(){Ve.call(this);this.set(191,new mh);this.set(150,new ph);this.set(146,new qh);this.set(147,new Kh);We(this,149,new Df);this.set(145,new tg);this.set(117,new wg);this.set(494,new Fg);this.set(374,new Gg);this.set(120,new Hg);this.set(121,new Ug);this.set(553,new Wg);this.set(124,new fh);this.set(125,new gh);this.set(123,new Yg);this.set(126,new kh);this.set(127,new lh);this.set(115,new Gf);this.set(118,new Pf);this.set(128,new hg);We(this,154,new sg);this.set(116,new sh);this.set(119,new xh);this.set(129,new Hh)}
w(Lh,Ve);function Mh(){return{nd:function(){return{Ld:"hp",we:"hp",Lh:"google.com",Qg:"",je:"en",hf:"",Rj:"",Ln:"",authuser:0,uj:"",Sg:"",tf:!1,tg:"",ve:"",Nd:0,transport:null,$g:!1,Dn:!1,dj:!1,Rh:!0,cn:10,Qh:!0,Sh:!0,Zm:!1,ki:!1,nj:!1,oj:!1,un:!1,$i:!0,Nh:!1,aj:500,Ri:!1,mn:!0,rn:!0,Fn:!1,Ti:!1,fg:"",wn:"//www.google.com/textinputassistant",xn:"",zn:7,nn:!1,pn:!1,Ui:!1,Si:!0,Vi:!1,Kf:!1,hk:!1,fk:!1,Tg:1,yj:!0,Vd:!1,fi:!1,Uh:!1,Qj:10,Oi:!1,Vj:!0,nb:document.body,Wi:!0,Rg:null,Vh:{},$m:{},An:0,mi:!1,ej:!0,Zb:!1,en:!1,Hn:null,Th:!1,vn:null,In:null,sf:!1,bj:!0,Hh:!1,Kn:1,Ij:!1,ik:"Search",hi:"I'm  Feeling Lucky",kk:"",sj:"Learn more",Cn:"Remove",Bn:"This search was removed from your Web History",tn:"",Ym:"Did you mean:",yn:"",En:"",On:"Search by voice",Nn:'Listening for "Ok Google"',Mn:'Say "Ok Google"',Wm:"Clear Search",hj:null,ij:0,jj:0,Pf:"",Ke:"",isRtl:!1,kd:"absolute",Pi:!1,Ni:!1,qg:null,Qi:!0,jd:[0,0,0],Oh:null,xk:null,Gh:[0],Gn:!0,Wg:"",yk:"",vk:"",fn:null,jn:"",hn:"",Um:1,ah:!1,vf:!1}}}}
;function Nh(a,b,c,d,e){var f=cf?"-moz-":af?"-ms-":df?"-o-":ef?"-webkit-":"",g=".gstl_"+d,l=new RegExp("(\\.("+e.join("|")+")\\b)"),m=[];return{addRule:function(a,d){if(b){if(c){a=a.split(",");for(var e=[],f=0,n;n=a[f++];)n=l.test(n)?n.replace(l,g+"$1"):g+" "+n,e.push(n);a=e.join(",")}m.push(a,"{",d,"}")}},Bh:function(){if(b&&m.length){b=!1;var c=qf("style");c.setAttribute("type","text/css");(a||Ae).appendChild(c);var d=m.join("");m=null;c.styleSheet?c.styleSheet.cssText=d:c.appendChild(document.createTextNode(d))}},prefix:function(a,b){var c=a+(b||"");f&&(c+=b?a+f+b:f+a);return c}}}
;function Oh(a,b,c){this.H=a;this.W=b;this.ha=c;this.w=-1;this.S=!1}
p=Oh.prototype;p.install=function(a){if(!this.S){a=Ph(a);0>this.w&&(this.w=Qh(a));var b=pf(this.H),c=Rh(this),d=!!b.getElementById("gs_id"+this.w),e=this,f=["gssb_c","gssb_k","sbdd_a","sbdd_c","sbib_a"];a.Wg&&f.push(a.Wg);f=Nh(a.Rg,a.Wi,a.Th,this.w,f);this.R=a.Zb;this.o=new Xe(this.W,this.ha,{Dh:function(){return d},get:function(a){return b.getElementById(a+e.w)},xf:function(a){return b.getElementById(a)},Bc:ba(null),$d:function(){return c},getId:function(a){return a+e.w},vi:function(){return e.H}},f,this,a);this.o.get(347);this.T=this.o.get(130);this.o.get(115);this.ka=this.o.get(117);this.o.get(123);this.o.get(118);this.V=this.o.get(119);this.o.get(374);this.o.get(120);this.o.get(189);this.o.get(553);this.o.get(419);this.o.get(126);this.ma=this.o.get(128);this.o.get(139);this.ra=this.o.get(121);Sh(this);this.S=!0}};p.activate=function(a){this.deactivate();a=Ph(a);this.R=a.Zb;this.o.activate(a)};p.deactivate=function(){this.o.deactivate()};p.focus=function(){this.V.focus()};p.getId=k("w");p.search=function(a,b){this.ra.search(a,b)};p.Zb=function(){return this.R||!!this.T&&this.T.Zb()};function Qh(a){a=uf(a.Rg||Ae);void 0==a.nextSearchboxId&&(a.nextSearchboxId=50);return a.nextSearchboxId++}
function Rh(a){if(a.H)for(a=a.H;a=a.parentNode;){var b=a.dir;if(b)return b}return"ltr"}
function Ph(a){a=Pe(a);var b=a.fg;b?a.fg=b.toLowerCase():a.Ti=!1;a.Vd&&!a.fi&&(a.Vd=!1);gf||(a.oj=!1);return a}
function Sh(a){var b=uf(a.H),c=tf(b);Dg(b,"resize",function(){var d=tf(b);if(d.xc!=c.xc||d.Lf!=c.Lf)c=d,Of(a.ka,8)})}
;function Th(){this.w=!1;this.H=null;this.o=new be}
w(Th,Ue);p=Th.prototype;p.install=function(a,b,c,d,e,f,g,l,m,n){n=n||"help";this.R=d;this.S=e;d=Mh().nd();"17"!=b&&"83757"!=b&&(d.tg=l||"www.google.com");d.Ld=n;d.we=n;d.hf=n;l=(l=c.match(/^\w{2,3}([-_]|$)/))?l[0].replace(/[_-]/g,""):"";d.je=l;l=c.split(/[-_]/g);(l=1<l.length&&l[1].match(/^[a-zA-Z]{4}$/)?l[1]:"")||(l=(c=c.match(/[-_]([a-zA-Z]{2}|\d{3})([-_]|$)/))?c[0].replace(/[_-]/g,""):"");d.Qg=l;m?d.qg=m:d.jd=[8,0,0];d.ah=!0;m=[0];f&&m.push(79);d.Jn=De(m);m=new Lh;We(m,156,new yf(b));We(m,152,new wf);We(m,152,new xf);m.set(157,new Cf);this.T=new Af(5,f,g);We(m,122,this.T);this.H=new Oh(a,this,m);this.H.install(d)};p.Uf=function(a){a.addRule(".sbdd_a","z-index: 1202")};p.search=function(a,b){1==b&&(this.w=!0);if((b=Vf(this.H.ma))&&79==b.Ga()){var c=b.getParameters();b=c.Wa("t");c=c.Wa("p");this.S&&this.S(b,c,a)}else this.R&&this.R(a)};p.rf=function(){this.w=!0;this.o.qd("OSC")};p.nf=function(){this.o.qd("OSS")};p.qf=function(){this.o.qd("OSH")};function Uh(a){var b={title:a.title,payload:a.Pa,purpose:a.Sj,category:a.Id,upload:a.Ub.filter(Vh).map(Wh),property:a.property,star:a.Kc};a.displayName&&(b.display_name=a.displayName);a.Jc&&(b.profile_exists=a.Jc);return new K("create_thread",b,function(a){return{Ba:a.thread_id}})}
v("module$exports$hcfe$forum$ForumService.createThread",Uh);function Xh(a){var b={thread_id:a.Ba,payload:a.Pa,upload:a.Ub.filter(Vh).map(Wh),subscribe:a.subscribe,type:a.type};a.displayName&&(b.display_name=a.displayName);a.Jc&&(b.profile_exists=a.Jc);return new K("create_message",b,function(a){return{Ka:a.message_id}})}
v("module$exports$hcfe$forum$ForumService.createMessage",Xh);function Yh(a){return new K("set_message_vote",{thread_id:a.Ba,message_id:a.Ka,vote:a.Oc,from_mail:a.ni})}
v("module$exports$hcfe$forum$ForumService.setMessageVote",Yh);function Zh(a){return new K("star_forum",{star:a.Kc})}
v("module$exports$hcfe$forum$ForumService.starForum",Zh);function $h(a){return new K("star_thread",{thread_id:a.Ba,star:a.Kc})}
v("module$exports$hcfe$forum$ForumService.starThread",$h);function ai(a){return new K("set_thread_vote",{thread_id:a.Ba,vote:a.Oc})}
v("module$exports$hcfe$forum$ForumService.setThreadVote",ai);function bi(a){return new K("delete_thread",{thread_id:a.Ba})}
v("module$exports$hcfe$forum$ForumService.deleteThread",bi);function ci(a){return new K("delete_message",{thread_id:a.Ba,message_id:a.Ka})}
v("module$exports$hcfe$forum$ForumService.deleteMessage",ci);function di(a){var b={};a.Ba&&(b.thread_id=a.Ba);a.Ka&&(b.message_id=a.Ka);a.og&&(b.profile_id=a.og);return new K("report_abuse",b)}
v("module$exports$hcfe$forum$ForumService.reportAbuse",di);function ei(a){return new K("set_message_type",{thread_id:a.Ba,message_id:a.Ka,type:a.type})}
v("module$exports$hcfe$forum$ForumService.setMessageType",ei);function fi(a){return new K("update_thread",{thread_id:a.Ba,title:a.title,payload:a.Pa,category:a.Id,upload:a.Ub.filter(Vh).map(Wh),property:a.property})}
v("module$exports$hcfe$forum$ForumService.updateThread",fi);function gi(a){return new K("update_message",{thread_id:a.Ba,message_id:a.Ka,payload:a.Pa,upload:a.Ub.filter(Vh).map(Wh)})}
v("module$exports$hcfe$forum$ForumService.updateMessage",gi);function hi(a){var b={name:a.name,abuse_reverted:a.zh,auto_generated:a.Fh};a.df&&(b.avatar=Wh(a.df));return new K("update_global_user_info",b)}
v("module$exports$hcfe$forum$ForumService.updateGlobalUserInfo",hi);function ii(a){return new K("validate_user_info",{name:a.name})}
v("module$exports$hcfe$forum$ForumService.validateUserInfo",ii);function ji(){return new K("get_default_user_info",{},function(a){var b={name:a.user.public_info.name,hb:a.user_profile_exists};a.user.private_info&&(b.wc=!1!==a.user.private_info.send_email_notifications);return b})}
v("module$exports$hcfe$forum$ForumService.getDefaultUserInfo",ji);function ki(a){return new K("unset_message_type",{thread_id:a.Ba,message_id:a.Ka})}
v("module$exports$hcfe$forum$ForumService.unsetMessageType",ki);function li(a){return new K("unset_message_vote",{thread_id:a.Ba,message_id:a.Ka,vote:a.Oc})}
v("module$exports$hcfe$forum$ForumService.unsetMessageVote",li);function mi(){return new K("delete_user_profile",{})}
v("module$exports$hcfe$forum$ForumService.deleteUserProfile",mi);function ni(a){return new K("update_global_user_info",{send_email_notifications:a.wc,send_google_bar_notifications:a.lk,subscribe_by_default:a.uk})}
v("module$exports$hcfe$forum$ForumService.updateNotificationPreferences",ni);function oi(a){return new K("set_thread_attribute",{thread_id:a.Ba,action:a.action})}
v("module$exports$hcfe$forum$ForumService.setThreadAttribute",oi);function pi(a){var b={thread_id:a.Ba};a.Ka&&(b.message_id=a.Ka);return new K("report_off_topic",b)}
v("module$exports$hcfe$forum$ForumService.reportOffTopic",pi);function qi(a){var b={thread_id:a.Ba};a.Ka&&(b.message_id=a.Ka);return new K("clear_off_topic",b)}
v("module$exports$hcfe$forum$ForumService.clearOffTopic",qi);function Wh(a){var b={original_filename:a.xd,document_id:a.jc};a.Fb&&(b.cns_path=a.Fb);a.hd&&(b.is_delete=!0);return b}
function Vh(a){return void 0!=a.Fb&&!a.hd||void 0==a.Fb&&a.hd}
function K(a,b,c){var d=this,e={};e[a]=b;B({httpMethod:"POST",endpoint:"forum",Xa:{resource:e,common_params:{context_params:{view_id:A().vid}}},params:{v:1},Na:function(b){try{if(b.responseText){try{var e=JSON.parse(b.responseText)}catch(l){ri(b.responseText);d.o&&d.o("INVALID_JSON","");return}if(e.error){d.o&&d.o(e.error.code,e.error.message||"");return}}else e=null;d.H&&d.H(c?c(e[a]):null)}finally{d.w&&d.w()}},ab:function(a){ri(a.responseText);d.o&&d.o("NETWORK_ERROR","");d.w&&d.w()}})}
K.prototype.Ea=function(a){this.H=a;return this};K.prototype.onResponse=K.prototype.Ea;K.prototype.onError=function(a){this.o=a;return this};K.prototype.onError=K.prototype.onError;K.prototype.Cb=function(a){this.w=a;return this};K.prototype.onFinish=K.prototype.Cb;function ri(a){window.sc_log&&window.sc_log("ForumService","ERROR",a)}
;function L(a){this.o=a;this.T="after";this.V="below";this.R=!0}
L.prototype.Ee=function(a){this.S=a;return this};L.prototype.setTrigger=L.prototype.Ee;L.prototype.Gg=function(a){this.T=a;return this};L.prototype.setHorizontalPosition=L.prototype.Gg;L.prototype.Mg=function(a){this.V=a;return this};L.prototype.setVerticalPosition=L.prototype.Mg;L.prototype.Ae=function(a){this.R=a;return this};L.prototype.setOverlapTrigger=L.prototype.Ae;L.prototype.open=function(){var a=this;this.w||(this.w=function(){return si(a)},window.addEventListener("resize",this.w),window.addEventListener("scroll",this.w));si(this);x(this.o,"popup--active",!0)};L.prototype.open=L.prototype.open;L.prototype.close=function(){x(this.o,"popup--active",!1);this.w&&(window.removeEventListener("resize",this.w),window.removeEventListener("scroll",this.w),this.w=void 0)};L.prototype.close=L.prototype.close;function si(a){a.H=a.S.getBoundingClientRect();var b=ti(a,"before"==a.T?["before","after"]:["after","before"]),c=ti(a,"above"==a.V?["above","below"]:["below","above"]);a.o.style.left=ui(a,b)+"px";a.o.style.top=ui(a,c)+"px";x(a.o,"popup--before","before"==b);x(a.o,"popup--after","after"==b);x(a.o,"popup--above","above"==c);x(a.o,"popup--below","below"==c)}
function ti(a,b){var c=b[0];b=q(b);for(var d=b.next();!d.done;d=b.next()){d=d.value;a:{var e=ui(a,d);switch(d){case "before":case "after":e=Math.min(e,0)+Math.min(window.innerWidth-e-a.o.offsetWidth,0);break a;case "above":case "below":e=Math.min(e,0)+Math.min(window.innerHeight-e-a.o.offsetHeight,0);break a}e=0}if(0<=e)return d;if(!f||f<e){c=d;var f=e}}return c}
function ui(a,b){var c=A().rtl;switch(b){case "before":return c?a.H.left:a.H.right-a.o.offsetWidth;case "after":return c?a.H.right-a.o.offsetWidth:a.H.left;case "above":return a.H.bottom-a.o.offsetHeight-a.S.offsetHeight*(a.R?0:1);case "below":return a.H.top+a.S.offsetHeight*(a.R?0:1)}return 0}
;
